

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceRecruitmentInformationMessage : Message
    {
        public const uint Id = 7840;
        public override uint MessageId => Id;
        
        public Types.AllianceRecruitmentInformation recruitmentData;
        
        public AllianceRecruitmentInformationMessage()
        { }
        
        public AllianceRecruitmentInformationMessage(Types.AllianceRecruitmentInformation recruitmentData)
        {
            this.recruitmentData = recruitmentData;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            recruitmentData.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            recruitmentData = new Types.AllianceRecruitmentInformation();
            recruitmentData.Deserialize(reader);
        }
    }
}