

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceFightPhaseUpdateMessage : Message
    {
        public const uint Id = 3190;
        public override uint MessageId => Id;
        
        public Types.SocialFightInfo allianceFightInfo;
        public Types.FightPhase newPhase;
        
        public AllianceFightPhaseUpdateMessage()
        { }
        
        public AllianceFightPhaseUpdateMessage(Types.SocialFightInfo allianceFightInfo, Types.FightPhase newPhase)
        {
            this.allianceFightInfo = allianceFightInfo;
            this.newPhase = newPhase;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            allianceFightInfo.Serialize(writer);
            newPhase.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            allianceFightInfo = new Types.SocialFightInfo();
            allianceFightInfo.Deserialize(reader);
            newPhase = new Types.FightPhase();
            newPhase.Deserialize(reader);
        }
    }
}