using System;
using System.Collections.Generic;
using Stump.Core.IO;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Spells
{
    public class SpellStateRelator
    {
        public static string FetchQuery = "SELECT * FROM spells_states";
    }

    [TableName("spells_states")]
    [D2OClass("SpellState", "com.ankamagames.dofus.datacenter.spells")]
    public sealed class SpellState : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;
        private uint[] m_effectsIds;
        private string m_effectsIdsCSV;

        [PrimaryKey("Id", false)]
        public int Id { get; set; }

        public uint NameId { get; set; }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
            set { m_name = value; }
        }

        public Boolean PreventsSpellCast { get; set; }

        public Boolean PreventsFight { get; set; }

        public Boolean IsSilent { get; set; }

        public Boolean CantDealDamage { get; set; }

        public Boolean Invulnerable { get; set; }

        public Boolean Incurable { get; set; }

        public Boolean CantBeMoved { get; set; }

        public Boolean CantBePushed { get; set; }

        public Boolean CantSwitchPosition { get; set; }

        [Ignore]
        public uint[] EffectsIds
        {
            get { return m_effectsIds; }
            set
            {
                m_effectsIds = value;
                m_effectsIdsCSV = value.ToCSV(",");
            }
        }

        public string EffectsIdsCSV
        {
            get { return m_effectsIdsCSV; }
            set
            {
                m_effectsIdsCSV = value;
                m_effectsIds = value.FromCSV<uint>(",");
            }
        }

        public string Icon { get; set; }

        public int IconVisibilityMask { get; set; }

        public Boolean InvulnerableMelee { get; set; }

        public Boolean InvulnerableRange { get; set; }

        public Boolean CantTackle { get; set; }

        public Boolean CantBeTackled { get; set; }

        public Boolean DisplayTurnRemaining { get; set; }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var state = (DofusProtocol.D2oClasses.SpellState)d2oObject;

            Id = state.id;
            NameId = state.nameId;
            Name = "";
            PreventsSpellCast = state.preventsSpellCast;
            PreventsFight = state.preventsFight;
            IsSilent = state.IsSilent;
            CantDealDamage = state.CantDealDamage;
            Invulnerable = state.Invulnerable;
            Incurable = state.Incurable;
            CantBeMoved = state.CantBeMoved;
            CantBePushed = state.CantBePushed;
            CantSwitchPosition = state.CantSwitchPosition;
            EffectsIds = state.effectsIds.ConvertAll(id => (uint)id).ToArray();
            Icon = state.icon;
            IconVisibilityMask = state.iconVisibilityMask;
            InvulnerableMelee = state.InvulnerableMelee;
            InvulnerableRange = state.InvulnerableRange;
            CantTackle = state.CantTackle;
            CantBeTackled = state.CantBeTackled;
            DisplayTurnRemaining = state.DisplayTurnRemaining;
        }

        #endregion
    }
}