

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HelloConnectMessage : Message
    {
        public const uint Id = 1657;
        public override uint MessageId => Id;
        
        public string salt;
        public IEnumerable<sbyte> key;
        
        public HelloConnectMessage()
        { }
        
        public HelloConnectMessage(string salt, IEnumerable<sbyte> key)
        {
            this.salt = salt;
            this.key = key;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(salt);
            writer.WriteVarInt((int)key.Count());
            foreach (var objectToSend in key)
            {
                 writer.WriteSByte(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            salt = reader.ReadUTF();
            var keyCount = reader.ReadVarInt();
            var key_ = new sbyte[keyCount];
            for (var keyIndex = 0; keyIndex < keyCount; keyIndex++)
            {
                 key_[keyIndex] = reader.ReadSByte();
            }
            key = key_;
        }
    }
}