

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class IdentificationMessage : Message
    {
        public const uint Id = 17;
        public override uint MessageId => Id;
        
        public bool autoconnect;
        public bool useCertificate;
        public bool useLoginToken;
        public Types.Version version;
        public string lang;
        public IEnumerable<sbyte> credentials;
        public short serverId;
        public long sessionOptionalSalt;
        public IEnumerable<ushort> failedAttempts;
        
        public IdentificationMessage()
        { }
        
        public IdentificationMessage(bool autoconnect, bool useCertificate, bool useLoginToken, Types.Version version, string lang, IEnumerable<sbyte> credentials, short serverId, long sessionOptionalSalt, IEnumerable<ushort> failedAttempts)
        {
            this.autoconnect = autoconnect;
            this.useCertificate = useCertificate;
            this.useLoginToken = useLoginToken;
            this.version = version;
            this.lang = lang;
            this.credentials = credentials;
            this.serverId = serverId;
            this.sessionOptionalSalt = sessionOptionalSalt;
            this.failedAttempts = failedAttempts;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, autoconnect);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, useCertificate);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 2, useLoginToken);
            writer.WriteByte(flag1);
            version.Serialize(writer);
            writer.WriteUTF(lang);
            writer.WriteVarInt((int)credentials.Count());
            foreach (var objectToSend in credentials)
            {
                 writer.WriteSByte(objectToSend);
            }
            writer.WriteShort(serverId);
            writer.WriteVarLong(sessionOptionalSalt);
            writer.WriteShort((short)failedAttempts.Count());
            foreach (var objectToSend in failedAttempts)
            {
                 writer.WriteVarUShort(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            byte flag1 = reader.ReadByte();
            autoconnect = BooleanByteWrapper.GetFlag(flag1, 0);
            useCertificate = BooleanByteWrapper.GetFlag(flag1, 1);
            useLoginToken = BooleanByteWrapper.GetFlag(flag1, 2);
            version = new Types.Version();
            version.Deserialize(reader);
            lang = reader.ReadUTF();
            var credentialsCount = reader.ReadVarInt();
            var credentials_ = new sbyte[credentialsCount];
            for (var credentialsIndex = 0; credentialsIndex < credentialsCount; credentialsIndex++)
            {
                 credentials_[credentialsIndex] = reader.ReadSByte();
            }
            credentials = credentials_;
            serverId = reader.ReadShort();
            sessionOptionalSalt = reader.ReadVarLong();
            var failedAttemptsCount = reader.ReadUShort();
            var failedAttempts_ = new ushort[failedAttemptsCount];
            for (var failedAttemptsIndex = 0; failedAttemptsIndex < failedAttemptsCount; failedAttemptsIndex++)
            {
                 failedAttempts_[failedAttemptsIndex] = reader.ReadVarUShort();
            }
            failedAttempts = failedAttempts_;
        }
    }
}