

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class StatsUpgradeResultMessage : Message
    {
        public const uint Id = 8116;
        public override uint MessageId => Id;
        
        public sbyte result;
        public ushort nbCharacBoost;
        
        public StatsUpgradeResultMessage()
        { }
        
        public StatsUpgradeResultMessage(sbyte result, ushort nbCharacBoost)
        {
            this.result = result;
            this.nbCharacBoost = nbCharacBoost;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(result);
            writer.WriteVarUShort(nbCharacBoost);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            result = reader.ReadSByte();
            nbCharacBoost = reader.ReadVarUShort();
        }
    }
}