

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class StatsUpgradeRequestMessage : Message
    {
        public const uint Id = 7474;
        public override uint MessageId => Id;
        
        public bool useAdditionnal;
        public sbyte statId;
        public ushort boostPoint;
        
        public StatsUpgradeRequestMessage()
        { }
        
        public StatsUpgradeRequestMessage(bool useAdditionnal, sbyte statId, ushort boostPoint)
        {
            this.useAdditionnal = useAdditionnal;
            this.statId = statId;
            this.boostPoint = boostPoint;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(useAdditionnal);
            writer.WriteSByte(statId);
            writer.WriteVarUShort(boostPoint);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            useAdditionnal = reader.ReadBoolean();
            statId = reader.ReadSByte();
            boostPoint = reader.ReadVarUShort();
        }
    }
}