

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class SpellModifierMessage
    {
        public const short Id = 2352;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ushort spellId;
        public sbyte actionType;
        public sbyte modifierType;
        public int context;
        public int equipment;
        
        public SpellModifierMessage()
        {
        }
        
        public SpellModifierMessage(ushort spellId, sbyte actionType, sbyte modifierType, int context, int equipment)
        {
            this.spellId = spellId;
            this.actionType = actionType;
            this.modifierType = modifierType;
            this.context = context;
            this.equipment = equipment;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(spellId);
            writer.WriteSByte(actionType);
            writer.WriteSByte(modifierType);
            writer.WriteInt(context);
            writer.WriteInt(equipment);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            spellId = reader.ReadVarUShort();
            actionType = reader.ReadSByte();
            modifierType = reader.ReadSByte();
            context = reader.ReadInt();
            equipment = reader.ReadInt();
        }
    }
}