

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class FriendsListMessage : Message
    {
        public const uint Id = 4516;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.FriendInformations> friendsList;
        
        public FriendsListMessage()
        { }
        
        public FriendsListMessage(IEnumerable<Types.FriendInformations> friendsList)
        {
            this.friendsList = friendsList;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)friendsList.Count());
            foreach (var objectToSend in friendsList)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var friendsListCount = reader.ReadUShort();
            var friendsList_ = new Types.FriendInformations[friendsListCount];
            for (var friendsListIndex = 0; friendsListIndex < friendsListCount; friendsListIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.FriendInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 friendsList_[friendsListIndex] = objectToAdd;
            }
            friendsList = friendsList_;
        }
    }
}