

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class IgnoredDeleteResultMessage : Message
    {
        public const uint Id = 6419;
        public override uint MessageId => Id;
        
        public bool success;
        public bool session;
        public Types.AccountTagInformation tag;
        
        public IgnoredDeleteResultMessage()
        { }
        
        public IgnoredDeleteResultMessage(bool success, bool session, Types.AccountTagInformation tag)
        {
            this.success = success;
            this.session = session;
            this.tag = tag;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, success);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, session);
            writer.WriteByte(flag1);
            tag.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            byte flag1 = reader.ReadByte();
            success = BooleanByteWrapper.GetFlag(flag1, 0);
            session = BooleanByteWrapper.GetFlag(flag1, 1);
            tag = new Types.AccountTagInformation();
            tag.Deserialize(reader);
        }
    }
}