

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class FinishMoveListMessage : Message
    {
        public const uint Id = 4314;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.FinishMoveInformations> finishMoves;
        
        public FinishMoveListMessage()
        { }
        
        public FinishMoveListMessage(IEnumerable<Types.FinishMoveInformations> finishMoves)
        {
            this.finishMoves = finishMoves;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)finishMoves.Count());
            foreach (var objectToSend in finishMoves)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var finishMovesCount = reader.ReadUShort();
            var finishMoves_ = new Types.FinishMoveInformations[finishMovesCount];
            for (var finishMovesIndex = 0; finishMovesIndex < finishMovesCount; finishMovesIndex++)
            {
                 var objectToAdd = new Types.FinishMoveInformations();
                 objectToAdd.Deserialize(reader);
                 finishMoves_[finishMovesIndex] = objectToAdd;
            }
            finishMoves = finishMoves_;
        }
    }
}