

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ArenaRankInfos
    {
        public const short Id = 9831;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public int arenaType;
        public Types.ArenaLeagueRanking leagueRanking;
        public short bestLeagueId;
        public int bestRating;
        public ushort dailyVictoryCount;
        public ushort seasonVictoryCount;
        public ushort dailyFightcount;
        public ushort seasonFightcount;
        public short numFightNeededForLadder;
        
        public ArenaRankInfos()
        {
        }
        
        public ArenaRankInfos(int arenaType, Types.ArenaLeagueRanking leagueRanking, short bestLeagueId, int bestRating, ushort dailyVictoryCount, ushort seasonVictoryCount, ushort dailyFightcount, ushort seasonFightcount, short numFightNeededForLadder)
        {
            this.arenaType = arenaType;
            this.leagueRanking = leagueRanking;
            this.bestLeagueId = bestLeagueId;
            this.bestRating = bestRating;
            this.dailyVictoryCount = dailyVictoryCount;
            this.seasonVictoryCount = seasonVictoryCount;
            this.dailyFightcount = dailyFightcount;
            this.seasonFightcount = seasonFightcount;
            this.numFightNeededForLadder = numFightNeededForLadder;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteInt(arenaType);
            leagueRanking.Serialize(writer);
            writer.WriteVarShort(bestLeagueId);
            writer.WriteInt(bestRating);
            writer.WriteVarUShort(dailyVictoryCount);
            writer.WriteVarUShort(seasonVictoryCount);
            writer.WriteVarUShort(dailyFightcount);
            writer.WriteVarUShort(seasonFightcount);
            writer.WriteShort(numFightNeededForLadder);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            arenaType = reader.ReadInt();
            leagueRanking = new Types.ArenaLeagueRanking();
            leagueRanking.Deserialize(reader);
            bestLeagueId = reader.ReadVarShort();
            bestRating = reader.ReadInt();
            dailyVictoryCount = reader.ReadVarUShort();
            seasonVictoryCount = reader.ReadVarUShort();
            dailyFightcount = reader.ReadVarUShort();
            seasonFightcount = reader.ReadVarUShort();
            numFightNeededForLadder = reader.ReadShort();
        }
    }
}