

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class LeagueFriendInformations : AbstractContactInformations
    {
        public const short Id = 6198;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ulong playerId;
        public string playerName;
        public sbyte breed;
        public bool sex;
        public ushort level;
        public short leagueId;
        public short totalLeaguePoints;
        public int ladderPosition;
        
        public LeagueFriendInformations()
        {
        }
        
        public LeagueFriendInformations(int accountId, Types.AccountTagInformation accountTag, ulong playerId, string playerName, sbyte breed, bool sex, ushort level, short leagueId, short totalLeaguePoints, int ladderPosition)
         : base(accountId, accountTag)
        {
            this.playerId = playerId;
            this.playerName = playerName;
            this.breed = breed;
            this.sex = sex;
            this.level = level;
            this.leagueId = leagueId;
            this.totalLeaguePoints = totalLeaguePoints;
            this.ladderPosition = ladderPosition;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(playerId);
            writer.WriteUTF(playerName);
            writer.WriteSByte(breed);
            writer.WriteBoolean(sex);
            writer.WriteVarUShort(level);
            writer.WriteVarShort(leagueId);
            writer.WriteVarShort(totalLeaguePoints);
            writer.WriteInt(ladderPosition);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            playerId = reader.ReadVarULong();
            playerName = reader.ReadUTF();
            breed = reader.ReadSByte();
            sex = reader.ReadBoolean();
            level = reader.ReadVarUShort();
            leagueId = reader.ReadVarShort();
            totalLeaguePoints = reader.ReadVarShort();
            ladderPosition = reader.ReadInt();
        }
    }
}