

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ChatClientPrivateWithObjectMessage : ChatClientPrivateMessage
    {
        public const uint Id = 3880;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.ObjectItem> objects;
        
        public ChatClientPrivateWithObjectMessage()
        { }
        
        public ChatClientPrivateWithObjectMessage(string content, Types.AbstractPlayerSearchInformation receiver, IEnumerable<Types.ObjectItem> objects)
         : base(content, receiver)
        {
            this.objects = objects;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)objects.Count());
            foreach (var objectToSend in objects)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var objectsCount = reader.ReadUShort();
            var objects_ = new Types.ObjectItem[objectsCount];
            for (var objectsIndex = 0; objectsIndex < objectsCount; objectsIndex++)
            {
                 var objectToAdd = new Types.ObjectItem();
                 objectToAdd.Deserialize(reader);
                 objects_[objectsIndex] = objectToAdd;
            }
            objects = objects_;
        }
    }
}