

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ChatAbstractServerMessage : Message
    {
        public const uint Id = 2152;
        public override uint MessageId => Id;
        
        public sbyte channel;
        public string content;
        public int timestamp;
        public string fingerprint;
        
        public ChatAbstractServerMessage()
        { }
        
        public ChatAbstractServerMessage(sbyte channel, string content, int timestamp, string fingerprint)
        {
            this.channel = channel;
            this.content = content;
            this.timestamp = timestamp;
            this.fingerprint = fingerprint;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(channel);
            writer.WriteUTF(content);
            writer.WriteInt(timestamp);
            writer.WriteUTF(fingerprint);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            channel = reader.ReadSByte();
            content = reader.ReadUTF();
            timestamp = reader.ReadInt();
            fingerprint = reader.ReadUTF();
        }
    }
}