using System;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Guilds
{
    public class EmblemRelator
    {
        public static string FetchQuery = "SELECT * FROM guilds_emblems";
    }

    [TableName("guilds_emblems")]
    [D2OClass("EmblemSymbol", "com.ankamagames.dofus.datacenter.guild")]
    public class EmblemRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        private int m_skin;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public int IconId
        {
            get;
            set;
        }

        public int SkinId
        {
            get
            {
                int skinConvert = SkinDifference(this.IconId, m_skin);

                return skinConvert;
            }
            set
            {
                m_skin = value;
            }
        }

        public int Order
        {
            get;
            set;
        }

        public int CategoryId
        {
            get;
            set;
        }

        public Boolean Colorizable
        {
            get;
            set;
        }

        private short SkinDifference(int iconId, int skinId)
        {
            int result = 0;

            if (iconId <= 104)
                result = skinId - 1026;
            else if (iconId >= 105 && iconId <= 154)
                result = skinId - 943;
            else if (iconId >= 155 && iconId <= 250)
                result = skinId - 942;
            else if (iconId >= 251 && iconId <= 323)
                result = skinId - 933;
            else if (iconId == 324)
                result = 2002;
            else if (iconId == 325)
                result = 3228;
            else if (iconId == 326)
                result = 3226;
            else if (iconId == 327)
                result = 3343;
            else if (iconId == 328)
                result = 3521;

            return (short)result;
        }

        public void AssignFields(object d2oObject)
        {
            var emblem = (EmblemSymbol)d2oObject;
            Id = emblem.Id;
            IconId = emblem.IconId;
            SkinId = emblem.SkinId;
            Order = emblem.Order;
            CategoryId = emblem.CategoryId;
            Colorizable = emblem.Colorizable;
        }
    }
}