

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class GameRolePlayGroupMonsterWaveInformations : GameRolePlayGroupMonsterInformations
    {
        public const short Id = 2546;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public sbyte nbWaves;
        public IEnumerable<Types.GroupMonsterStaticInformations> alternatives;
        
        public GameRolePlayGroupMonsterWaveInformations()
        {
        }
        
        public GameRolePlayGroupMonsterWaveInformations(double contextualId, Types.EntityDispositionInformations disposition, Types.EntityLook look, Types.GroupMonsterStaticInformations staticInfos, sbyte lootShare, sbyte alignmentSide, bool hasHardcoreDrop, sbyte nbWaves, IEnumerable<Types.GroupMonsterStaticInformations> alternatives)
         : base(contextualId, disposition, look, staticInfos, lootShare, alignmentSide, hasHardcoreDrop)
        {
            this.nbWaves = nbWaves;
            this.alternatives = alternatives;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(nbWaves);
            writer.WriteShort((short)alternatives.Count());
            foreach (var objectToSend in alternatives)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            nbWaves = reader.ReadSByte();
            var alternativesCount = reader.ReadUShort();
            var alternatives_ = new Types.GroupMonsterStaticInformations[alternativesCount];
            for (var alternativesIndex = 0; alternativesIndex < alternativesCount; alternativesIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.GroupMonsterStaticInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 alternatives_[alternativesIndex] = objectToAdd;
            }
            alternatives = alternatives_;
        }
    }
}