

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class HumanOptionFollowers : HumanOption
    {
        public const short Id = 7033;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public IEnumerable<Types.IndexedEntityLook> followingCharactersLook;
        
        public HumanOptionFollowers()
        {
        }
        
        public HumanOptionFollowers(IEnumerable<Types.IndexedEntityLook> followingCharactersLook)
        {
            this.followingCharactersLook = followingCharactersLook;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)followingCharactersLook.Count());
            foreach (var objectToSend in followingCharactersLook)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var followingCharactersLookCount = reader.ReadUShort();
            var followingCharactersLook_ = new Types.IndexedEntityLook[followingCharactersLookCount];
            for (var followingCharactersLookIndex = 0; followingCharactersLookIndex < followingCharactersLookCount; followingCharactersLookIndex++)
            {
                 var objectToAdd = new Types.IndexedEntityLook();
                 objectToAdd.Deserialize(reader);
                 followingCharactersLook_[followingCharactersLookIndex] = objectToAdd;
            }
            followingCharactersLook = followingCharactersLook_;
        }
    }
}