

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AccountSubscriptionElapsedDurationMessage : Message
    {
        public const uint Id = 2680;
        public override uint MessageId => Id;
        
        public double subscriptionElapsedDuration;
        
        public AccountSubscriptionElapsedDurationMessage()
        { }
        
        public AccountSubscriptionElapsedDurationMessage(double subscriptionElapsedDuration)
        {
            this.subscriptionElapsedDuration = subscriptionElapsedDuration;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(subscriptionElapsedDuration);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            subscriptionElapsedDuration = reader.ReadDouble();
        }
    }
}