

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class FightPhase
    {
        public const short Id = 9523;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public sbyte phase;
        public double phaseEndTimeStamp;
        
        public FightPhase()
        {
        }
        
        public FightPhase(sbyte phase, double phaseEndTimeStamp)
        {
            this.phase = phase;
            this.phaseEndTimeStamp = phaseEndTimeStamp;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(phase);
            writer.WriteDouble(phaseEndTimeStamp);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            phase = reader.ReadSByte();
            phaseEndTimeStamp = reader.ReadDouble();
        }
    }
}