

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class FightResultPlayerListEntry : FightResultFighterListEntry
    {
        public const short Id = 1387;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ushort level;
        public IEnumerable<Types.FightResultAdditionalData> additional;
        
        public FightResultPlayerListEntry()
        {
        }
        
        public FightResultPlayerListEntry(ushort outcome, sbyte wave, Types.FightLoot rewards, double id, bool alive, ushort level, IEnumerable<Types.FightResultAdditionalData> additional)
         : base(outcome, wave, rewards, id, alive)
        {
            this.level = level;
            this.additional = additional;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUShort(level);
            writer.WriteShort((short)additional.Count());
            foreach (var objectToSend in additional)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            level = reader.ReadVarUShort();
            var additionalCount = reader.ReadUShort();
            var additional_ = new Types.FightResultAdditionalData[additionalCount];
            for (var additionalIndex = 0; additionalIndex < additionalCount; additionalIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.FightResultAdditionalData>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 additional_[additionalIndex] = objectToAdd;
            }
            additional = additional_;
        }
    }
}