

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class GameContextSummonsInformation
    {
        public const short Id = 1255;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public Types.SpawnInformation spawnInformation;
        public sbyte wave;
        public Types.EntityLook look;
        public Types.GameFightCharacteristics stats;
        public IEnumerable<Types.GameContextBasicSpawnInformation> summons;
        
        public GameContextSummonsInformation()
        {
        }
        
        public GameContextSummonsInformation(Types.SpawnInformation spawnInformation, sbyte wave, Types.EntityLook look, Types.GameFightCharacteristics stats, IEnumerable<Types.GameContextBasicSpawnInformation> summons)
        {
            this.spawnInformation = spawnInformation;
            this.wave = wave;
            this.look = look;
            this.stats = stats;
            this.summons = summons;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteShort(spawnInformation.TypeId);
            spawnInformation.Serialize(writer);
            writer.WriteSByte(wave);
            look.Serialize(writer);
            writer.WriteShort(stats.TypeId);
            stats.Serialize(writer);
            writer.WriteShort((short)summons.Count());
            foreach (var objectToSend in summons)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            spawnInformation = Types.ProtocolTypeManager.GetInstance<Types.SpawnInformation>(reader.ReadShort());
            spawnInformation.Deserialize(reader);
            wave = reader.ReadSByte();
            look = new Types.EntityLook();
            look.Deserialize(reader);
            stats = Types.ProtocolTypeManager.GetInstance<Types.GameFightCharacteristics>(reader.ReadShort());
            stats.Deserialize(reader);
            var summonsCount = reader.ReadUShort();
            var summons_ = new Types.GameContextBasicSpawnInformation[summonsCount];
            for (var summonsIndex = 0; summonsIndex < summonsCount; summonsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.GameContextBasicSpawnInformation>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 summons_[summonsIndex] = objectToAdd;
            }
            summons = summons_;
        }
    }
}