

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class SpawnCompanionInformation : SpawnInformation
    {
        public const short Id = 5676;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public sbyte modelId;
        public ushort level;
        public double summonerId;
        public double ownerId;
        
        public SpawnCompanionInformation()
        {
        }
        
        public SpawnCompanionInformation(sbyte modelId, ushort level, double summonerId, double ownerId)
        {
            this.modelId = modelId;
            this.level = level;
            this.summonerId = summonerId;
            this.ownerId = ownerId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(modelId);
            writer.WriteVarUShort(level);
            writer.WriteDouble(summonerId);
            writer.WriteDouble(ownerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            modelId = reader.ReadSByte();
            level = reader.ReadVarUShort();
            summonerId = reader.ReadDouble();
            ownerId = reader.ReadDouble();
        }
    }
}