

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameRolePlayPlayerFightFriendlyRequestedMessage : Message
    {
        public const uint Id = 4876;
        public override uint MessageId => Id;
        
        public ushort fightId;
        public ulong sourceId;
        public ulong targetId;
        
        public GameRolePlayPlayerFightFriendlyRequestedMessage()
        { }
        
        public GameRolePlayPlayerFightFriendlyRequestedMessage(ushort fightId, ulong sourceId, ulong targetId)
        {
            this.fightId = fightId;
            this.sourceId = sourceId;
            this.targetId = targetId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(fightId);
            writer.WriteVarULong(sourceId);
            writer.WriteVarULong(targetId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightId = reader.ReadVarUShort();
            sourceId = reader.ReadVarULong();
            targetId = reader.ReadVarULong();
        }
    }
}