

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ExtendedLockedBreachBranch : ExtendedBreachBranch
    {
        public const short Id = 5890;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public uint unlockPrice;
        
        public ExtendedLockedBreachBranch()
        {
        }
        
        public ExtendedLockedBreachBranch(sbyte room, int element, IEnumerable<Types.MonsterInGroupLightInformations> bosses, double map, short score, short relativeScore, IEnumerable<Types.MonsterInGroupLightInformations> monsters, IEnumerable<Types.BreachReward> rewards, int modifier, uint prize, uint unlockPrice)
         : base(room, element, bosses, map, score, relativeScore, monsters, rewards, modifier, prize)
        {
            this.unlockPrice = unlockPrice;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUInt(unlockPrice);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            unlockPrice = reader.ReadVarUInt();
        }
    }
}