

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ExtendedBreachBranch : BreachBranch
    {
        public const short Id = 6771;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public IEnumerable<Types.BreachReward> rewards;
        public int modifier;
        public uint prize;
        
        public ExtendedBreachBranch()
        {
        }
        
        public ExtendedBreachBranch(sbyte room, int element, IEnumerable<Types.MonsterInGroupLightInformations> bosses, double map, short score, short relativeScore, IEnumerable<Types.MonsterInGroupLightInformations> monsters, IEnumerable<Types.BreachReward> rewards, int modifier, uint prize)
         : base(room, element, bosses, map, score, relativeScore, monsters)
        {
            this.rewards = rewards;
            this.modifier = modifier;
            this.prize = prize;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)rewards.Count());
            foreach (var objectToSend in rewards)
            {
                 objectToSend.Serialize(writer);
            }
            writer.WriteVarInt(modifier);
            writer.WriteVarUInt(prize);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var rewardsCount = reader.ReadUShort();
            var rewards_ = new Types.BreachReward[rewardsCount];
            for (var rewardsIndex = 0; rewardsIndex < rewardsCount; rewardsIndex++)
            {
                 var objectToAdd = new Types.BreachReward();
                 objectToAdd.Deserialize(reader);
                 rewards_[rewardsIndex] = objectToAdd;
            }
            rewards = rewards_;
            modifier = reader.ReadVarInt();
            prize = reader.ReadVarUInt();
        }
    }
}