

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameDataPaddockObjectListAddMessage : Message
    {
        public const uint Id = 4187;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.PaddockItem> paddockItemDescription;
        
        public GameDataPaddockObjectListAddMessage()
        { }
        
        public GameDataPaddockObjectListAddMessage(IEnumerable<Types.PaddockItem> paddockItemDescription)
        {
            this.paddockItemDescription = paddockItemDescription;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)paddockItemDescription.Count());
            foreach (var objectToSend in paddockItemDescription)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var paddockItemDescriptionCount = reader.ReadUShort();
            var paddockItemDescription_ = new Types.PaddockItem[paddockItemDescriptionCount];
            for (var paddockItemDescriptionIndex = 0; paddockItemDescriptionIndex < paddockItemDescriptionCount; paddockItemDescriptionIndex++)
            {
                 var objectToAdd = new Types.PaddockItem();
                 objectToAdd.Deserialize(reader);
                 paddockItemDescription_[paddockItemDescriptionIndex] = objectToAdd;
            }
            paddockItemDescription = paddockItemDescription_;
        }
    }
}