

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class MountFeedRequestMessage : Message
    {
        public const uint Id = 5031;
        public override uint MessageId => Id;
        
        public uint mountUid;
        public sbyte mountLocation;
        public uint mountFoodUid;
        public uint quantity;
        
        public MountFeedRequestMessage()
        { }
        
        public MountFeedRequestMessage(uint mountUid, sbyte mountLocation, uint mountFoodUid, uint quantity)
        {
            this.mountUid = mountUid;
            this.mountLocation = mountLocation;
            this.mountFoodUid = mountFoodUid;
            this.quantity = quantity;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(mountUid);
            writer.WriteSByte(mountLocation);
            writer.WriteVarUInt(mountFoodUid);
            writer.WriteVarUInt(quantity);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            mountUid = reader.ReadVarUInt();
            mountLocation = reader.ReadSByte();
            mountFoodUid = reader.ReadVarUInt();
            quantity = reader.ReadVarUInt();
        }
    }
}