

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PaddockBuyResultMessage : Message
    {
        public const uint Id = 335;
        public override uint MessageId => Id;
        
        public double paddockId;
        public bool bought;
        public ulong realPrice;
        
        public PaddockBuyResultMessage()
        { }
        
        public PaddockBuyResultMessage(double paddockId, bool bought, ulong realPrice)
        {
            this.paddockId = paddockId;
            this.bought = bought;
            this.realPrice = realPrice;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(paddockId);
            writer.WriteBoolean(bought);
            writer.WriteVarULong(realPrice);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            paddockId = reader.ReadDouble();
            bought = reader.ReadBoolean();
            realPrice = reader.ReadVarULong();
        }
    }
}