

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class CharacterLevelUpMessage : Message
    {
        public const uint Id = 4096;
        public override uint MessageId => Id;
        
        public ushort newLevel;
        
        public CharacterLevelUpMessage()
        { }
        
        public CharacterLevelUpMessage(ushort newLevel)
        {
            this.newLevel = newLevel;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(newLevel);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            newLevel = reader.ReadVarUShort();
        }
    }
}