

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ReportRequestMessage : Message
    {
        public const uint Id = 6032;
        public override uint MessageId => Id;
        
        public double targetId;
        public IEnumerable<sbyte> categories;
        public string description;
        
        public ReportRequestMessage()
        { }
        
        public ReportRequestMessage(double targetId, IEnumerable<sbyte> categories, string description)
        {
            this.targetId = targetId;
            this.categories = categories;
            this.description = description;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(targetId);
            writer.WriteShort((short)categories.Count());
            foreach (var objectToSend in categories)
            {
                 writer.WriteSByte(objectToSend);
            }
            writer.WriteUTF(description);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            targetId = reader.ReadDouble();
            var categoriesCount = reader.ReadUShort();
            var categories_ = new sbyte[categoriesCount];
            for (var categoriesIndex = 0; categoriesIndex < categoriesCount; categoriesIndex++)
            {
                 categories_[categoriesIndex] = reader.ReadSByte();
            }
            categories = categories_;
            description = reader.ReadUTF();
        }
    }
}