

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class QuestActiveInformations
    {
        public const short Id = 1335;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ushort questId;
        
        public QuestActiveInformations()
        {
        }
        
        public QuestActiveInformations(ushort questId)
        {
            this.questId = questId;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(questId);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            questId = reader.ReadVarUShort();
        }
    }
}