

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class RemoveSpellModifierMessage : Message
    {
        public const uint Id = 139;
        public override uint MessageId => Id;
        
        public double actorId;
        public sbyte actionType;
        public sbyte modifierType;
        public ushort spellId;
        
        public RemoveSpellModifierMessage()
        { }
        
        public RemoveSpellModifierMessage(double actorId, sbyte actionType, sbyte modifierType, ushort spellId)
        {
            this.actorId = actorId;
            this.actionType = actionType;
            this.modifierType = modifierType;
            this.spellId = spellId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(actorId);
            writer.WriteSByte(actionType);
            writer.WriteSByte(modifierType);
            writer.WriteVarUShort(spellId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            actorId = reader.ReadDouble();
            actionType = reader.ReadSByte();
            modifierType = reader.ReadSByte();
            spellId = reader.ReadVarUShort();
        }
    }
}