using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Startup
{
    [TableName("command_to_console")]
    public class CommandToConsole : AutoAssignedRecord<StartupActionRecordItems>, IAutoGeneratedRecord
    {
        //   [PrimaryKey("Command")]
        public string Command { get; set; }

        public int OwnerId { get; set; }
        public int RoleId { get; set; }

    }
}