

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AllianceMemberInfo : SocialMember
    {
        public const short Id = 9446;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public int avaRoleId;
        
        public AllianceMemberInfo()
        {
        }
        
        public AllianceMemberInfo(ulong id, string name, ushort level, sbyte breed, bool sex, sbyte connected, ushort hoursSinceLastConnection, int accountId, Types.PlayerStatus status, int rankId, double enrollmentDate, int avaRoleId)
         : base(id, name, level, breed, sex, connected, hoursSinceLastConnection, accountId, status, rankId, enrollmentDate)
        {
            this.avaRoleId = avaRoleId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(avaRoleId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            avaRoleId = reader.ReadInt();
        }
    }
}