

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class SocialFightTakePlaceRequestMessage : Message
    {
        public const uint Id = 2458;
        public override uint MessageId => Id;
        
        public Types.SocialFightInfo socialFightInfo;
        public ulong replacedCharacterId;
        
        public SocialFightTakePlaceRequestMessage()
        { }
        
        public SocialFightTakePlaceRequestMessage(Types.SocialFightInfo socialFightInfo, ulong replacedCharacterId)
        {
            this.socialFightInfo = socialFightInfo;
            this.replacedCharacterId = replacedCharacterId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            socialFightInfo.Serialize(writer);
            writer.WriteVarULong(replacedCharacterId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            socialFightInfo = new Types.SocialFightInfo();
            socialFightInfo.Deserialize(reader);
            replacedCharacterId = reader.ReadVarULong();
        }
    }
}