

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameContextCreateMessage : Message
    {
        public const uint Id = 5863;
        public override uint MessageId => Id;
        
        public sbyte context;
        
        public GameContextCreateMessage()
        { }
        
        public GameContextCreateMessage(sbyte context)
        {
            this.context = context;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(context);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            context = reader.ReadSByte();
        }
    }
}