

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class DebugHighlightCellsMessage : Message
    {
        public const uint Id = 2076;
        public override uint MessageId => Id;
        
        public double color;
        public IEnumerable<ushort> cells;
        
        public DebugHighlightCellsMessage()
        { }
        
        public DebugHighlightCellsMessage(double color, IEnumerable<ushort> cells)
        {
            this.color = color;
            this.cells = cells;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(color);
            writer.WriteShort((short)cells.Count());
            foreach (var objectToSend in cells)
            {
                 writer.WriteVarUShort(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            color = reader.ReadDouble();
            var cellsCount = reader.ReadUShort();
            var cells_ = new ushort[cellsCount];
            for (var cellsIndex = 0; cellsIndex < cellsCount; cellsIndex++)
            {
                 cells_[cellsIndex] = reader.ReadVarUShort();
            }
            cells = cells_;
        }
    }
}