

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class PaddockContentInformations : PaddockInformations
    {
        public const short Id = 8721;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public double paddockId;
        public short worldX;
        public short worldY;
        public double mapId;
        public ushort subAreaId;
        public bool abandonned;
        public IEnumerable<Types.MountInformationsForPaddock> mountsInformations;
        
        public PaddockContentInformations()
        {
        }
        
        public PaddockContentInformations(ushort maxOutdoorMount, ushort maxItems, double paddockId, short worldX, short worldY, double mapId, ushort subAreaId, bool abandonned, IEnumerable<Types.MountInformationsForPaddock> mountsInformations)
         : base(maxOutdoorMount, maxItems)
        {
            this.paddockId = paddockId;
            this.worldX = worldX;
            this.worldY = worldY;
            this.mapId = mapId;
            this.subAreaId = subAreaId;
            this.abandonned = abandonned;
            this.mountsInformations = mountsInformations;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteDouble(paddockId);
            writer.WriteShort(worldX);
            writer.WriteShort(worldY);
            writer.WriteDouble(mapId);
            writer.WriteVarUShort(subAreaId);
            writer.WriteBoolean(abandonned);
            writer.WriteShort((short)mountsInformations.Count());
            foreach (var objectToSend in mountsInformations)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            paddockId = reader.ReadDouble();
            worldX = reader.ReadShort();
            worldY = reader.ReadShort();
            mapId = reader.ReadDouble();
            subAreaId = reader.ReadVarUShort();
            abandonned = reader.ReadBoolean();
            var mountsInformationsCount = reader.ReadUShort();
            var mountsInformations_ = new Types.MountInformationsForPaddock[mountsInformationsCount];
            for (var mountsInformationsIndex = 0; mountsInformationsIndex < mountsInformationsCount; mountsInformationsIndex++)
            {
                 var objectToAdd = new Types.MountInformationsForPaddock();
                 objectToAdd.Deserialize(reader);
                 mountsInformations_[mountsInformationsIndex] = objectToAdd;
            }
            mountsInformations = mountsInformations_;
        }
    }
}