

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class PaddockInformations
    {
        public const short Id = 3212;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ushort maxOutdoorMount;
        public ushort maxItems;
        
        public PaddockInformations()
        {
        }
        
        public PaddockInformations(ushort maxOutdoorMount, ushort maxItems)
        {
            this.maxOutdoorMount = maxOutdoorMount;
            this.maxItems = maxItems;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(maxOutdoorMount);
            writer.WriteVarUShort(maxItems);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            maxOutdoorMount = reader.ReadVarUShort();
            maxItems = reader.ReadVarUShort();
        }
    }
}