

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class NuggetsDistributionMessage : Message
    {
        public const uint Id = 7391;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.NuggetsBeneficiary> beneficiaries;
        
        public NuggetsDistributionMessage()
        { }
        
        public NuggetsDistributionMessage(IEnumerable<Types.NuggetsBeneficiary> beneficiaries)
        {
            this.beneficiaries = beneficiaries;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)beneficiaries.Count());
            foreach (var objectToSend in beneficiaries)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var beneficiariesCount = reader.ReadUShort();
            var beneficiaries_ = new Types.NuggetsBeneficiary[beneficiariesCount];
            for (var beneficiariesIndex = 0; beneficiariesIndex < beneficiariesCount; beneficiariesIndex++)
            {
                 var objectToAdd = new Types.NuggetsBeneficiary();
                 objectToAdd.Deserialize(reader);
                 beneficiaries_[beneficiariesIndex] = objectToAdd;
            }
            beneficiaries = beneficiaries_;
        }
    }
}