

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class BasicAckMessage : Message
    {
        public const uint Id = 4642;
        public override uint MessageId => Id;
        
        public uint seq;
        public ushort lastPacketId;
        
        public BasicAckMessage()
        { }
        
        public BasicAckMessage(uint seq, ushort lastPacketId)
        {
            this.seq = seq;
            this.lastPacketId = lastPacketId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(seq);
            writer.WriteVarUShort(lastPacketId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            seq = reader.ReadVarUInt();
            lastPacketId = reader.ReadVarUShort();
        }
    }
}