

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TextInformationMessage : Message
    {
        public const uint Id = 3946;
        public override uint MessageId => Id;
        
        public sbyte msgType;
        public ushort msgId;
        public IEnumerable<string> parameters;
        
        public TextInformationMessage()
        { }
        
        public TextInformationMessage(sbyte msgType, ushort msgId, IEnumerable<string> parameters)
        {
            this.msgType = msgType;
            this.msgId = msgId;
            this.parameters = parameters;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(msgType);
            writer.WriteVarUShort(msgId);
            writer.WriteShort((short)parameters.Count());
            foreach (var objectToSend in parameters)
            {
                 writer.WriteUTF(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            msgType = reader.ReadSByte();
            msgId = reader.ReadVarUShort();
            var parametersCount = reader.ReadUShort();
            var parameters_ = new string[parametersCount];
            for (var parametersIndex = 0; parametersIndex < parametersCount; parametersIndex++)
            {
                 parameters_[parametersIndex] = reader.ReadUTF();
            }
            parameters = parameters_;
        }
    }
}