

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class InteractiveUseErrorMessage : Message
    {
        public const uint Id = 7919;
        public override uint MessageId => Id;
        
        public uint elemId;
        public uint skillInstanceUid;
        
        public InteractiveUseErrorMessage()
        { }
        
        public InteractiveUseErrorMessage(uint elemId, uint skillInstanceUid)
        {
            this.elemId = elemId;
            this.skillInstanceUid = skillInstanceUid;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(elemId);
            writer.WriteVarUInt(skillInstanceUid);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            elemId = reader.ReadVarUInt();
            skillInstanceUid = reader.ReadVarUInt();
        }
    }
}