

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class InventoryWeightMessage : Message
    {
        public const uint Id = 9175;
        public override uint MessageId => Id;
        
        public uint inventoryWeight;
        public uint weightMax;
        
        public InventoryWeightMessage()
        { }
        
        public InventoryWeightMessage(uint inventoryWeight, uint weightMax)
        {
            this.inventoryWeight = inventoryWeight;
            this.weightMax = weightMax;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(inventoryWeight);
            writer.WriteVarUInt(weightMax);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            inventoryWeight = reader.ReadVarUInt();
            weightMax = reader.ReadVarUInt();
        }
    }
}