

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class LivingObjectChangeSkinRequestMessage : Message
    {
        public const uint Id = 9449;
        public override uint MessageId => Id;
        
        public uint livingUID;
        public byte livingPosition;
        public uint skinId;
        
        public LivingObjectChangeSkinRequestMessage()
        { }
        
        public LivingObjectChangeSkinRequestMessage(uint livingUID, byte livingPosition, uint skinId)
        {
            this.livingUID = livingUID;
            this.livingPosition = livingPosition;
            this.skinId = skinId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(livingUID);
            writer.WriteByte(livingPosition);
            writer.WriteVarUInt(skinId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            livingUID = reader.ReadVarUInt();
            livingPosition = reader.ReadByte();
            skinId = reader.ReadVarUInt();
        }
    }
}