using Stump.Core.IO;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;
using System;

namespace Stump.Server.WorldServer.Database.World
{
    public class WorldMapRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM world_worldmaps";
    }

    [TableName("world_worldmaps")]
    [D2OClass("WorldMap", "com.ankamagames.dofus.datacenter.world")]
    public sealed class WorldMapRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;
        private string[] m_zoom;
        private string m_zoomCSV;

        [PrimaryKey("Id", false)]
        public int Id { get; set; }

        public uint NameId { get; set; }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
            set { m_name = value; }
        }

        public int OrigineX { get; set; }

        public int OrigineY { get; set; }

        public double MapWidth { get; set; }

        public double MapHeight { get; set; }

        public bool ViewableEverywhere { get; set; }

        public double MinScale { get; set; }

        public double MaxScale { get; set; }

        public double StartScale { get; set; }

        public int TotalWidth { get; set; }

        public int TotalHeight { get; set; }

        [Ignore]
        public string[] Zoom
        {
            get { return m_zoom; }
            set
            {
                m_zoom = value;
                m_zoomCSV = value.ToCSV(",");
            }
        }

        public string ZoomCSV
        {
            get { return m_zoomCSV; }
            set
            {
                m_zoomCSV = value;
                m_zoom = value.FromCSV<string>(",");
            }
        }

        public Boolean VisibleOnMap { get; set; }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var map = (WorldMap)d2oObject;

            Id = map.id;
            NameId = map.nameId;
            Name = "";
            OrigineX = map.origineX;
            OrigineY = map.origineY;
            MapWidth = map.mapWidth;
            MapHeight = map.mapHeight;
            ViewableEverywhere = map.viewableEverywhere;
            MinScale = map.minScale;
            MaxScale = map.maxScale;
            StartScale = map.startScale;
            TotalWidth = map.totalWidth;
            TotalHeight = map.totalHeight;
            Zoom = map.Zoom.ToArray();
            VisibleOnMap = map.VisibleOnMap;
        }

        #endregion
    }
}