

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class NotificationListMessage : Message
    {
        public const uint Id = 1568;
        public override uint MessageId => Id;
        
        public IEnumerable<int> flags;
        
        public NotificationListMessage()
        { }
        
        public NotificationListMessage(IEnumerable<int> flags)
        {
            this.flags = flags;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)flags.Count());
            foreach (var objectToSend in flags)
            {
                 writer.WriteVarInt(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var flagsCount = reader.ReadUShort();
            var flags_ = new int[flagsCount];
            for (var flagsIndex = 0; flagsIndex < flagsCount; flagsIndex++)
            {
                 flags_[flagsIndex] = reader.ReadVarInt();
            }
            flags = flags_;
        }
    }
}