

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class NotificationUpdateFlagMessage : Message
    {
        public const uint Id = 1553;
        public override uint MessageId => Id;
        
        public ushort index;
        
        public NotificationUpdateFlagMessage()
        { }
        
        public NotificationUpdateFlagMessage(ushort index)
        {
            this.index = index;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(index);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            index = reader.ReadVarUShort();
        }
    }
}