

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class CharacterCharacteristicDetailed : CharacterCharacteristic
    {
        public const short Id = 2881;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public int @base;
        public int additional;
        public int objectsAndMountBonus;
        public int alignGiftBonus;
        public int contextModif;
        
        public CharacterCharacteristicDetailed()
        {
        }
        
        public CharacterCharacteristicDetailed(int contextModif, int @base, int alignGiftBonus, short characteristicId, int objectsAndMountBonus, int additional) : base(characteristicId)
        {
            this.@base = @base;
            this.additional = additional;
            this.objectsAndMountBonus = objectsAndMountBonus;
            this.alignGiftBonus = alignGiftBonus;
            this.contextModif = contextModif;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarInt(@base);
            writer.WriteVarInt(additional);
            writer.WriteVarInt(objectsAndMountBonus);
            writer.WriteVarInt(alignGiftBonus);
            writer.WriteVarInt(contextModif);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            @base = reader.ReadVarInt();
            additional = reader.ReadVarInt();
            objectsAndMountBonus = reader.ReadVarInt();
            alignGiftBonus = reader.ReadVarInt();
            contextModif = reader.ReadVarInt();
        }
    }
}