

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class BasicStatWithDataMessage : BasicStatMessage
    {
        public const uint Id = 9212;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.StatisticData> datas;
        
        public BasicStatWithDataMessage()
        { }
        
        public BasicStatWithDataMessage(double timeSpent, ushort statId, IEnumerable<Types.StatisticData> datas)
         : base(timeSpent, statId)
        {
            this.datas = datas;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)datas.Count());
            foreach (var objectToSend in datas)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var datasCount = reader.ReadUShort();
            var datas_ = new Types.StatisticData[datasCount];
            for (var datasIndex = 0; datasIndex < datasCount; datasIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.StatisticData>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 datas_[datasIndex] = objectToAdd;
            }
            datas = datas_;
        }
    }
}