using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Database.Kolilog
{
    [TableName("koli_log")]
    public class koli_logRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }

        // public string Fighter_Id { get; set; }        
        public DateTime Time { get; set; }

        public int Koli_Type { get; set; }

        public string Ip_own { get; set; }

        public string Hardware_own { get; set; }

        public string Ip_opponent { get; set; }

        public string Hardware_opponent { get; set; }

        [Ignore]
        public bool IsNew { get; set; }
    }
}
