

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AdditionalTaxCollectorInformation
    {
        public const short Id = 21;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ulong collectorCallerId;
        public string collectorCallerName;
        public int date;
        
        public AdditionalTaxCollectorInformation()
        {
        }
        
        public AdditionalTaxCollectorInformation(ulong collectorCallerId, string collectorCallerName, int date)
        {
            this.collectorCallerId = collectorCallerId;
            this.collectorCallerName = collectorCallerName;
            this.date = date;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(collectorCallerId);
            writer.WriteUTF(collectorCallerName);
            writer.WriteInt(date);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            collectorCallerId = reader.ReadVarULong();
            collectorCallerName = reader.ReadUTF();
            date = reader.ReadInt();
        }
    }
}