

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("Spell", "com.ankamagames.dofus.datacenter.spells")]
    [Serializable]
    public class Spell : IDataObject, IIndexedData
    {
        public const String MODULE = "Spells";
        public int id;
        [I18NField]
        public uint nameId;
        [I18NField]
        public uint descriptionId;
        public uint typeId;
        public uint order;
        public List<BoundScriptUsageData> boundScriptUsageData;
        public List<BoundScriptUsageData> criticalHitBoundScriptUsageData;
        public int iconId;
        public List<uint> spellLevels;
        public Boolean useParamCache = true;
        public Boolean verboseCast;
        public String defaultPreviewZone;
        public Boolean bypassSummoningLimit;
        public Boolean canAlwaysTriggerSpells;
        public String adminName;
        public Boolean hideCastConditions;
        int IIndexedData.Id
        {
            get { return (int)id; }
        }
        [D2OIgnore]
        public int Id
        {
            get { return this.id; }
            set { this.id = value; }
        }
        [D2OIgnore]
        public uint NameId
        {
            get { return this.nameId; }
            set { this.nameId = value; }
        }
        [D2OIgnore]
        public uint DescriptionId
        {
            get { return this.descriptionId; }
            set { this.descriptionId = value; }
        }
        [D2OIgnore]
        public uint TypeId
        {
            get { return this.typeId; }
            set { this.typeId = value; }
        }
        [D2OIgnore]
        public uint Order
        {
            get { return this.order; }
            set { this.order = value; }
        }
        [D2OIgnore]
        public List<BoundScriptUsageData> BoundScriptUsageData
        {
            get { return this.boundScriptUsageData; }
            set { this.boundScriptUsageData = value; }
        }
        [D2OIgnore]
        public List<BoundScriptUsageData> CriticalHitBoundScriptUsageData
        {
            get { return this.criticalHitBoundScriptUsageData; }
            set { this.criticalHitBoundScriptUsageData = value; }
        }
        [D2OIgnore]
        public int IconId
        {
            get { return this.iconId; }
            set { this.iconId = value; }
        }
        [D2OIgnore]
        public List<uint> SpellLevels
        {
            get { return this.spellLevels; }
            set { this.spellLevels = value; }
        }
        [D2OIgnore]
        public Boolean UseParamCache
        {
            get { return this.useParamCache; }
            set { this.useParamCache = value; }
        }
        [D2OIgnore]
        public Boolean VerboseCast
        {
            get { return this.verboseCast; }
            set { this.verboseCast = value; }
        }
        [D2OIgnore]
        public String DefaultPreviewZone
        {
            get { return this.defaultPreviewZone; }
            set { this.defaultPreviewZone = value; }
        }
        [D2OIgnore]
        public Boolean BypassSummoningLimit
        {
            get { return this.bypassSummoningLimit; }
            set { this.bypassSummoningLimit = value; }
        }
        [D2OIgnore]
        public Boolean CanAlwaysTriggerSpells
        {
            get { return this.canAlwaysTriggerSpells; }
            set { this.canAlwaysTriggerSpells = value; }
        }
        [D2OIgnore]
        public String AdminName
        {
            get { return this.adminName; }
            set { this.adminName = value; }
        }
        [D2OIgnore]
        public Boolean HideCastConditions
        {
            get { return this.hideCastConditions; }
            set { this.hideCastConditions = value; }
        }
    }
}