

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildBulletinSetRequestMessage : SocialNoticeSetRequestMessage
    {
        public const uint Id = 8237;
        public override uint MessageId => Id;
        
        public string content;
        
        public GuildBulletinSetRequestMessage()
        { }
        
        public GuildBulletinSetRequestMessage(string content)
        {
            this.content = content;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUTF(content);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            content = reader.ReadUTF();
        }
    }
}