

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildInformationsGeneralMessage : Message
    {
        public const uint Id = 1991;
        public override uint MessageId => Id;
        
        public bool abandonnedPaddock;
        public byte level;
        public ulong expLevelFloor;
        public ulong experience;
        public ulong expNextLevelFloor;
        public int creationDate;
        public int score;
        
        public GuildInformationsGeneralMessage()
        { }
        
        public GuildInformationsGeneralMessage(bool abandonnedPaddock, byte level, ulong expLevelFloor, ulong experience, ulong expNextLevelFloor, int creationDate, int score)
        {
            this.abandonnedPaddock = abandonnedPaddock;
            this.level = level;
            this.expLevelFloor = expLevelFloor;
            this.experience = experience;
            this.expNextLevelFloor = expNextLevelFloor;
            this.creationDate = creationDate;
            this.score = score;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(abandonnedPaddock);
            writer.WriteByte(level);
            writer.WriteVarULong(expLevelFloor);
            writer.WriteVarULong(experience);
            writer.WriteVarULong(expNextLevelFloor);
            writer.WriteInt(creationDate);
            writer.WriteInt(score);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            abandonnedPaddock = reader.ReadBoolean();
            level = reader.ReadByte();
            expLevelFloor = reader.ReadVarULong();
            experience = reader.ReadVarULong();
            expNextLevelFloor = reader.ReadVarULong();
            creationDate = reader.ReadInt();
            score = reader.ReadInt();
        }
    }
}