

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildSummaryRequestMessage : PaginationRequestAbstractMessage
    {
        public const uint Id = 4368;
        public override uint MessageId => Id;
        
        public bool hideFullFilter;
        public bool followingGuildCriteria;
        public bool sortDescending;
        public string nameFilter;
        public IEnumerable<uint> criterionFilter;
        public IEnumerable<uint> languagesFilter;
        public IEnumerable<sbyte> recruitmentTypeFilter;
        public short minLevelFilter;
        public short maxLevelFilter;
        public short minPlayerLevelFilter;
        public short maxPlayerLevelFilter;
        public uint minSuccessFilter;
        public uint maxSuccessFilter;
        public sbyte sortType;
        
        public GuildSummaryRequestMessage()
        { }
        
        public GuildSummaryRequestMessage(double offset, uint count, bool hideFullFilter, bool followingGuildCriteria, bool sortDescending, string nameFilter, IEnumerable<uint> criterionFilter, IEnumerable<uint> languagesFilter, IEnumerable<sbyte> recruitmentTypeFilter, short minLevelFilter, short maxLevelFilter, short minPlayerLevelFilter, short maxPlayerLevelFilter, uint minSuccessFilter, uint maxSuccessFilter, sbyte sortType)
         : base(offset, count)
        {
            this.hideFullFilter = hideFullFilter;
            this.followingGuildCriteria = followingGuildCriteria;
            this.sortDescending = sortDescending;
            this.nameFilter = nameFilter;
            this.criterionFilter = criterionFilter;
            this.languagesFilter = languagesFilter;
            this.recruitmentTypeFilter = recruitmentTypeFilter;
            this.minLevelFilter = minLevelFilter;
            this.maxLevelFilter = maxLevelFilter;
            this.minPlayerLevelFilter = minPlayerLevelFilter;
            this.maxPlayerLevelFilter = maxPlayerLevelFilter;
            this.minSuccessFilter = minSuccessFilter;
            this.maxSuccessFilter = maxSuccessFilter;
            this.sortType = sortType;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, hideFullFilter);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, followingGuildCriteria);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 2, sortDescending);
            writer.WriteByte(flag1);
            writer.WriteUTF(nameFilter);
            writer.WriteShort((short)criterionFilter.Count());
            foreach (var objectToSend in criterionFilter)
            {
                 writer.WriteVarUInt(objectToSend);
            }
            writer.WriteShort((short)languagesFilter.Count());
            foreach (var objectToSend in languagesFilter)
            {
                 writer.WriteVarUInt(objectToSend);
            }
            writer.WriteShort((short)recruitmentTypeFilter.Count());
            foreach (var objectToSend in recruitmentTypeFilter)
            {
                 writer.WriteSByte(objectToSend);
            }
            writer.WriteShort(minLevelFilter);
            writer.WriteShort(maxLevelFilter);
            writer.WriteShort(minPlayerLevelFilter);
            writer.WriteShort(maxPlayerLevelFilter);
            writer.WriteVarUInt(minSuccessFilter);
            writer.WriteVarUInt(maxSuccessFilter);
            writer.WriteSByte(sortType);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            byte flag1 = reader.ReadByte();
            hideFullFilter = BooleanByteWrapper.GetFlag(flag1, 0);
            followingGuildCriteria = BooleanByteWrapper.GetFlag(flag1, 1);
            sortDescending = BooleanByteWrapper.GetFlag(flag1, 2);
            nameFilter = reader.ReadUTF();
            var criterionFilterCount = reader.ReadUShort();
            var criterionFilter_ = new uint[criterionFilterCount];
            for (var criterionFilterIndex = 0; criterionFilterIndex < criterionFilterCount; criterionFilterIndex++)
            {
                 criterionFilter_[criterionFilterIndex] = reader.ReadVarUInt();
            }
            criterionFilter = criterionFilter_;
            var languagesFilterCount = reader.ReadUShort();
            var languagesFilter_ = new uint[languagesFilterCount];
            for (var languagesFilterIndex = 0; languagesFilterIndex < languagesFilterCount; languagesFilterIndex++)
            {
                 languagesFilter_[languagesFilterIndex] = reader.ReadVarUInt();
            }
            languagesFilter = languagesFilter_;
            var recruitmentTypeFilterCount = reader.ReadUShort();
            var recruitmentTypeFilter_ = new sbyte[recruitmentTypeFilterCount];
            for (var recruitmentTypeFilterIndex = 0; recruitmentTypeFilterIndex < recruitmentTypeFilterCount; recruitmentTypeFilterIndex++)
            {
                 recruitmentTypeFilter_[recruitmentTypeFilterIndex] = reader.ReadSByte();
            }
            recruitmentTypeFilter = recruitmentTypeFilter_;
            minLevelFilter = reader.ReadShort();
            maxLevelFilter = reader.ReadShort();
            minPlayerLevelFilter = reader.ReadShort();
            maxPlayerLevelFilter = reader.ReadShort();
            minSuccessFilter = reader.ReadVarUInt();
            maxSuccessFilter = reader.ReadVarUInt();
            sortType = reader.ReadSByte();
        }
    }
}