

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ChallengeListMessage : Message
    {
        public const uint Id = 1098;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.ChallengeInformation> challengesInformation;
        
        public ChallengeListMessage()
        { }
        
        public ChallengeListMessage(IEnumerable<Types.ChallengeInformation> challengesInformation)
        {
            this.challengesInformation = challengesInformation;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)challengesInformation.Count());
            foreach (var objectToSend in challengesInformation)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var challengesInformationCount = reader.ReadUShort();
            var challengesInformation_ = new Types.ChallengeInformation[challengesInformationCount];
            for (var challengesInformationIndex = 0; challengesInformationIndex < challengesInformationCount; challengesInformationIndex++)
            {
                 var objectToAdd = new Types.ChallengeInformation();
                 objectToAdd.Deserialize(reader);
                 challengesInformation_[challengesInformationIndex] = objectToAdd;
            }
            challengesInformation = challengesInformation_;
        }
    }
}