

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ChallengeSelectedMessage : Message
    {
        public const uint Id = 26;
        public override uint MessageId => Id;
        
        public Types.ChallengeInformation challengeInformation;
        
        public ChallengeSelectedMessage()
        { }
        
        public ChallengeSelectedMessage(Types.ChallengeInformation challengeInformation)
        {
            this.challengeInformation = challengeInformation;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            challengeInformation.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            challengeInformation = new Types.ChallengeInformation();
            challengeInformation.Deserialize(reader);
        }
    }
}