

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ChallengeBonusChoiceMessage : Message
    {
        public const uint Id = 6752;
        public override uint MessageId => Id;
        
        public sbyte challengeBonus;
        
        public ChallengeBonusChoiceMessage()
        { }
        
        public ChallengeBonusChoiceMessage(sbyte challengeBonus)
        {
            this.challengeBonus = challengeBonus;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(challengeBonus);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            challengeBonus = reader.ReadSByte();
        }
    }
}