

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class PartyInvitationMemberInformations : CharacterBaseInformations
    {
        public const short Id = 8078;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public short worldX;
        public short worldY;
        public double mapId;
        public ushort subAreaId;
        public IEnumerable<Types.PartyEntityBaseInformation> entities;
        
        public PartyInvitationMemberInformations()
        {
        }
        
        public PartyInvitationMemberInformations(ulong id, string name, ushort level, Types.EntityLook entityLook, sbyte breed, bool sex, short prestige, short worldX, short worldY, double mapId, ushort subAreaId, IEnumerable<Types.PartyEntityBaseInformation> entities)
         : base(id, name, level, entityLook, breed, sex, prestige)
        {
            this.worldX = worldX;
            this.worldY = worldY;
            this.mapId = mapId;
            this.subAreaId = subAreaId;
            this.entities = entities;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(worldX);
            writer.WriteShort(worldY);
            writer.WriteDouble(mapId);
            writer.WriteVarUShort(subAreaId);
            writer.WriteShort((short)entities.Count());
            foreach (var objectToSend in entities)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            worldX = reader.ReadShort();
            worldY = reader.ReadShort();
            mapId = reader.ReadDouble();
            subAreaId = reader.ReadVarUShort();
            var entitiesCount = reader.ReadUShort();
            var entities_ = new Types.PartyEntityBaseInformation[entitiesCount];
            for (var entitiesIndex = 0; entitiesIndex < entitiesCount; entitiesIndex++)
            {
                 var objectToAdd = new Types.PartyEntityBaseInformation();
                 objectToAdd.Deserialize(reader);
                 entities_[entitiesIndex] = objectToAdd;
            }
            entities = entities_;
        }
    }
}