

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class PartyGuestInformations
    {
        public const short Id = 8732;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ulong guestId;
        public ulong hostId;
        public string name;
        public Types.EntityLook guestLook;
        public sbyte breed;
        public bool sex;
        public Types.PlayerStatus status;
        public IEnumerable<Types.PartyEntityBaseInformation> entities;
        
        public PartyGuestInformations()
        {
        }
        
        public PartyGuestInformations(ulong guestId, ulong hostId, string name, Types.EntityLook guestLook, sbyte breed, bool sex, Types.PlayerStatus status, IEnumerable<Types.PartyEntityBaseInformation> entities)
        {
            this.guestId = guestId;
            this.hostId = hostId;
            this.name = name;
            this.guestLook = guestLook;
            this.breed = breed;
            this.sex = sex;
            this.status = status;
            this.entities = entities;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(guestId);
            writer.WriteVarULong(hostId);
            writer.WriteUTF(name);
            guestLook.Serialize(writer);
            writer.WriteSByte(breed);
            writer.WriteBoolean(sex);
            writer.WriteShort(status.TypeId);
            status.Serialize(writer);
            writer.WriteShort((short)entities.Count());
            foreach (var objectToSend in entities)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            guestId = reader.ReadVarULong();
            hostId = reader.ReadVarULong();
            name = reader.ReadUTF();
            guestLook = new Types.EntityLook();
            guestLook.Deserialize(reader);
            breed = reader.ReadSByte();
            sex = reader.ReadBoolean();
            status = Types.ProtocolTypeManager.GetInstance<Types.PlayerStatus>(reader.ReadShort());
            status.Deserialize(reader);
            var entitiesCount = reader.ReadUShort();
            var entities_ = new Types.PartyEntityBaseInformation[entitiesCount];
            for (var entitiesIndex = 0; entitiesIndex < entitiesCount; entitiesIndex++)
            {
                 var objectToAdd = new Types.PartyEntityBaseInformation();
                 objectToAdd.Deserialize(reader);
                 entities_[entitiesIndex] = objectToAdd;
            }
            entities = entities_;
        }
    }
}