

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class PartyMemberInformations : CharacterBaseInformations
    {
        public const short Id = 7120;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public uint lifePoints;
        public uint maxLifePoints;
        public uint prospecting;
        public byte regenRate;
        public uint initiative;
        public sbyte alignmentSide;
        public short worldX;
        public short worldY;
        public double mapId;
        public ushort subAreaId;
        public Types.PlayerStatus status;
        public IEnumerable<Types.PartyEntityBaseInformation> entities;
        
        public PartyMemberInformations()
        {
        }
        
        public PartyMemberInformations(ulong id, string name, ushort level, Types.EntityLook entityLook, sbyte breed, bool sex, short prestige, uint lifePoints, uint maxLifePoints, uint prospecting, byte regenRate, uint initiative, sbyte alignmentSide, short worldX, short worldY, double mapId, ushort subAreaId, Types.PlayerStatus status, IEnumerable<Types.PartyEntityBaseInformation> entities)
         : base(id, name, level, entityLook, breed, sex, prestige)
        {
            this.lifePoints = lifePoints;
            this.maxLifePoints = maxLifePoints;
            this.prospecting = prospecting;
            this.regenRate = regenRate;
            this.initiative = initiative;
            this.alignmentSide = alignmentSide;
            this.worldX = worldX;
            this.worldY = worldY;
            this.mapId = mapId;
            this.subAreaId = subAreaId;
            this.status = status;
            this.entities = entities;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUInt(lifePoints);
            writer.WriteVarUInt(maxLifePoints);
            writer.WriteVarUInt(prospecting);
            writer.WriteByte(regenRate);
            writer.WriteVarUInt(initiative);
            writer.WriteSByte(alignmentSide);
            writer.WriteShort(worldX);
            writer.WriteShort(worldY);
            writer.WriteDouble(mapId);
            writer.WriteVarUShort(subAreaId);
            writer.WriteShort(status.TypeId);
            status.Serialize(writer);
            writer.WriteShort((short)entities.Count());
            foreach (var objectToSend in entities)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            lifePoints = reader.ReadVarUInt();
            maxLifePoints = reader.ReadVarUInt();
            prospecting = reader.ReadVarUInt();
            regenRate = reader.ReadByte();
            initiative = reader.ReadVarUInt();
            alignmentSide = reader.ReadSByte();
            worldX = reader.ReadShort();
            worldY = reader.ReadShort();
            mapId = reader.ReadDouble();
            subAreaId = reader.ReadVarUShort();
            status = Types.ProtocolTypeManager.GetInstance<Types.PlayerStatus>(reader.ReadShort());
            status.Deserialize(reader);
            var entitiesCount = reader.ReadUShort();
            var entities_ = new Types.PartyEntityBaseInformation[entitiesCount];
            for (var entitiesIndex = 0; entitiesIndex < entitiesCount; entitiesIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.PartyEntityBaseInformation>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 entities_[entitiesIndex] = objectToAdd;
            }
            entities = entities_;
        }
    }
}