

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class GuildRankActivity : GuildLogbookEntryBasicInformation
    {
        public const short Id = 303;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public sbyte rankActivityType;
        public Types.RankMinimalInformation guildRankMinimalInfos;
        
        public GuildRankActivity()
        {
        }
        
        public GuildRankActivity(uint id, double date, sbyte rankActivityType, Types.RankMinimalInformation guildRankMinimalInfos)
         : base(id, date)
        {
            this.rankActivityType = rankActivityType;
            this.guildRankMinimalInfos = guildRankMinimalInfos;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(rankActivityType);
            guildRankMinimalInfos.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            rankActivityType = reader.ReadSByte();
            guildRankMinimalInfos = new Types.RankMinimalInformation();
            guildRankMinimalInfos.Deserialize(reader);
        }
    }
}