

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class InvalidPresetsMessage : Message
    {
        public const uint Id = 8794;
        public override uint MessageId => Id;
        
        public IEnumerable<short> presetIds;
        
        public InvalidPresetsMessage()
        { }
        
        public InvalidPresetsMessage(IEnumerable<short> presetIds)
        {
            this.presetIds = presetIds;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)presetIds.Count());
            foreach (var objectToSend in presetIds)
            {
                 writer.WriteShort(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var presetIdsCount = reader.ReadUShort();
            var presetIds_ = new short[presetIdsCount];
            for (var presetIdsIndex = 0; presetIdsIndex < presetIdsCount; presetIdsIndex++)
            {
                 presetIds_[presetIdsIndex] = reader.ReadShort();
            }
            presetIds = presetIds_;
        }
    }
}