

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PresetUseResultWithMissingIdsMessage : PresetUseResultMessage
    {
        public const uint Id = 6242;
        public override uint MessageId => Id;
        
        public IEnumerable<ushort> missingIds;
        
        public PresetUseResultWithMissingIdsMessage()
        { }
        
        public PresetUseResultWithMissingIdsMessage(short presetId, sbyte code, IEnumerable<ushort> missingIds)
         : base(presetId, code)
        {
            this.missingIds = missingIds;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)missingIds.Count());
            foreach (var objectToSend in missingIds)
            {
                 writer.WriteVarUShort(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var missingIdsCount = reader.ReadUShort();
            var missingIds_ = new ushort[missingIdsCount];
            for (var missingIdsIndex = 0; missingIdsIndex < missingIdsCount; missingIdsIndex++)
            {
                 missingIds_[missingIdsIndex] = reader.ReadVarUShort();
            }
            missingIds = missingIds_;
        }
    }
}