

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PresetsMessage : Message
    {
        public const uint Id = 8776;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.Preset> presets;
        
        public PresetsMessage()
        { }
        
        public PresetsMessage(IEnumerable<Types.Preset> presets)
        {
            this.presets = presets;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)presets.Count());
            foreach (var objectToSend in presets)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var presetsCount = reader.ReadUShort();
            var presets_ = new Types.Preset[presetsCount];
            for (var presetsIndex = 0; presetsIndex < presetsCount; presetsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.Preset>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 presets_[presetsIndex] = objectToAdd;
            }
            presets = presets_;
        }
    }
}