

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class JobDescription
    {
        public const short Id = 9860;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public sbyte jobId;
        public IEnumerable<Types.SkillActionDescription> skills;
        
        public JobDescription()
        {
        }
        
        public JobDescription(sbyte jobId, IEnumerable<Types.SkillActionDescription> skills)
        {
            this.jobId = jobId;
            this.skills = skills;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(jobId);
            writer.WriteShort((short)skills.Count());
            foreach (var objectToSend in skills)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            jobId = reader.ReadSByte();
            var skillsCount = reader.ReadUShort();
            var skills_ = new Types.SkillActionDescription[skillsCount];
            for (var skillsIndex = 0; skillsIndex < skillsCount; skillsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.SkillActionDescription>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 skills_[skillsIndex] = objectToAdd;
            }
            skills = skills_;
        }
    }
}