

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class JobExperience
    {
        public const short Id = 3823;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public sbyte jobId;
        public byte jobLevel;
        public ulong jobXP;
        public ulong jobXpLevelFloor;
        public ulong jobXpNextLevelFloor;
        
        public JobExperience()
        {
        }
        
        public JobExperience(sbyte jobId, byte jobLevel, ulong jobXP, ulong jobXpLevelFloor, ulong jobXpNextLevelFloor)
        {
            this.jobId = jobId;
            this.jobLevel = jobLevel;
            this.jobXP = jobXP;
            this.jobXpLevelFloor = jobXpLevelFloor;
            this.jobXpNextLevelFloor = jobXpNextLevelFloor;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(jobId);
            writer.WriteByte(jobLevel);
            writer.WriteVarULong(jobXP);
            writer.WriteVarULong(jobXpLevelFloor);
            writer.WriteVarULong(jobXpNextLevelFloor);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            jobId = reader.ReadSByte();
            jobLevel = reader.ReadByte();
            jobXP = reader.ReadVarULong();
            jobXpLevelFloor = reader.ReadVarULong();
            jobXpNextLevelFloor = reader.ReadVarULong();
        }
    }
}