

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AnomalySubareaInformationResponseMessage : Message
    {
        public const uint Id = 4744;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.AnomalySubareaInformation> subareas;
        
        public AnomalySubareaInformationResponseMessage()
        { }
        
        public AnomalySubareaInformationResponseMessage(IEnumerable<Types.AnomalySubareaInformation> subareas)
        {
            this.subareas = subareas;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)subareas.Count());
            foreach (var objectToSend in subareas)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var subareasCount = reader.ReadUShort();
            var subareas_ = new Types.AnomalySubareaInformation[subareasCount];
            for (var subareasIndex = 0; subareasIndex < subareasCount; subareasIndex++)
            {
                 var objectToAdd = new Types.AnomalySubareaInformation();
                 objectToAdd.Deserialize(reader);
                 subareas_[subareasIndex] = objectToAdd;
            }
            subareas = subareas_;
        }
    }
}