

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class MapComplementaryInformationsDataMessage : Message
    {
        public const uint Id = 6795;
        public override uint MessageId => Id;
        
        public ushort subAreaId;
        public double mapId;
        public IEnumerable<Types.HouseInformations> houses;
        public IEnumerable<Types.GameRolePlayActorInformations> actors;
        public IEnumerable<Types.InteractiveElement> interactiveElements;
        public IEnumerable<Types.StatedElement> statedElements;
        public IEnumerable<Types.MapObstacle> obstacles;
        public IEnumerable<Types.FightCommonInformations> fights;
        public bool hasAggressiveMonsters;
        public Types.FightStartingPositions fightStartPositions;
        
        public MapComplementaryInformationsDataMessage()
        { }
        
        public MapComplementaryInformationsDataMessage(ushort subAreaId, double mapId, IEnumerable<Types.HouseInformations> houses, IEnumerable<Types.GameRolePlayActorInformations> actors, IEnumerable<Types.InteractiveElement> interactiveElements, IEnumerable<Types.StatedElement> statedElements, IEnumerable<Types.MapObstacle> obstacles, IEnumerable<Types.FightCommonInformations> fights, bool hasAggressiveMonsters, Types.FightStartingPositions fightStartPositions)
        {
            this.subAreaId = subAreaId;
            this.mapId = mapId;
            this.houses = houses;
            this.actors = actors;
            this.interactiveElements = interactiveElements;
            this.statedElements = statedElements;
            this.obstacles = obstacles;
            this.fights = fights;
            this.hasAggressiveMonsters = hasAggressiveMonsters;
            this.fightStartPositions = fightStartPositions;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(subAreaId);
            writer.WriteDouble(mapId);
            writer.WriteShort((short)houses.Count());
            foreach (var objectToSend in houses)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)actors.Count());
            foreach (var objectToSend in actors)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)interactiveElements.Count());
            foreach (var objectToSend in interactiveElements)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)statedElements.Count());
            foreach (var objectToSend in statedElements)
            {
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)obstacles.Count());
            foreach (var objectToSend in obstacles)
            {
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)fights.Count());
            foreach (var objectToSend in fights)
            {
                 objectToSend.Serialize(writer);
            }
            writer.WriteBoolean(hasAggressiveMonsters);
            fightStartPositions.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            subAreaId = reader.ReadVarUShort();
            mapId = reader.ReadDouble();
            var housesCount = reader.ReadUShort();
            var houses_ = new Types.HouseInformations[housesCount];
            for (var housesIndex = 0; housesIndex < housesCount; housesIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.HouseInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 houses_[housesIndex] = objectToAdd;
            }
            houses = houses_;
            var actorsCount = reader.ReadUShort();
            var actors_ = new Types.GameRolePlayActorInformations[actorsCount];
            for (var actorsIndex = 0; actorsIndex < actorsCount; actorsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.GameRolePlayActorInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 actors_[actorsIndex] = objectToAdd;
            }
            actors = actors_;
            var interactiveElementsCount = reader.ReadUShort();
            var interactiveElements_ = new Types.InteractiveElement[interactiveElementsCount];
            for (var interactiveElementsIndex = 0; interactiveElementsIndex < interactiveElementsCount; interactiveElementsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.InteractiveElement>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 interactiveElements_[interactiveElementsIndex] = objectToAdd;
            }
            interactiveElements = interactiveElements_;
            var statedElementsCount = reader.ReadUShort();
            var statedElements_ = new Types.StatedElement[statedElementsCount];
            for (var statedElementsIndex = 0; statedElementsIndex < statedElementsCount; statedElementsIndex++)
            {
                 var objectToAdd = new Types.StatedElement();
                 objectToAdd.Deserialize(reader);
                 statedElements_[statedElementsIndex] = objectToAdd;
            }
            statedElements = statedElements_;
            var obstaclesCount = reader.ReadUShort();
            var obstacles_ = new Types.MapObstacle[obstaclesCount];
            for (var obstaclesIndex = 0; obstaclesIndex < obstaclesCount; obstaclesIndex++)
            {
                 var objectToAdd = new Types.MapObstacle();
                 objectToAdd.Deserialize(reader);
                 obstacles_[obstaclesIndex] = objectToAdd;
            }
            obstacles = obstacles_;
            var fightsCount = reader.ReadUShort();
            var fights_ = new Types.FightCommonInformations[fightsCount];
            for (var fightsIndex = 0; fightsIndex < fightsCount; fightsIndex++)
            {
                 var objectToAdd = new Types.FightCommonInformations();
                 objectToAdd.Deserialize(reader);
                 fights_[fightsIndex] = objectToAdd;
            }
            fights = fights_;
            hasAggressiveMonsters = reader.ReadBoolean();
            fightStartPositions = new Types.FightStartingPositions();
            fightStartPositions.Deserialize(reader);
        }
    }
}