

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class MapFightCountMessage : Message
    {
        public const uint Id = 213;
        public override uint MessageId => Id;
        
        public ushort fightCount;
        
        public MapFightCountMessage()
        { }
        
        public MapFightCountMessage(ushort fightCount)
        {
            this.fightCount = fightCount;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(fightCount);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightCount = reader.ReadVarUShort();
        }
    }
}