

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class MapRunningFightDetailsExtendedMessage : MapRunningFightDetailsMessage
    {
        public const uint Id = 1491;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.NamedPartyTeam> namedPartyTeams;
        
        public MapRunningFightDetailsExtendedMessage()
        { }
        
        public MapRunningFightDetailsExtendedMessage(ushort fightId, IEnumerable<Types.GameFightFighterLightInformations> attackers, IEnumerable<Types.GameFightFighterLightInformations> defenders, IEnumerable<Types.NamedPartyTeam> namedPartyTeams)
         : base(fightId, attackers, defenders)
        {
            this.namedPartyTeams = namedPartyTeams;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)namedPartyTeams.Count());
            foreach (var objectToSend in namedPartyTeams)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var namedPartyTeamsCount = reader.ReadUShort();
            var namedPartyTeams_ = new Types.NamedPartyTeam[namedPartyTeamsCount];
            for (var namedPartyTeamsIndex = 0; namedPartyTeamsIndex < namedPartyTeamsCount; namedPartyTeamsIndex++)
            {
                 var objectToAdd = new Types.NamedPartyTeam();
                 objectToAdd.Deserialize(reader);
                 namedPartyTeams_[namedPartyTeamsIndex] = objectToAdd;
            }
            namedPartyTeams = namedPartyTeams_;
        }
    }
}