

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class MapRunningFightDetailsMessage : Message
    {
        public const uint Id = 8907;
        public override uint MessageId => Id;
        
        public ushort fightId;
        public IEnumerable<Types.GameFightFighterLightInformations> attackers;
        public IEnumerable<Types.GameFightFighterLightInformations> defenders;
        
        public MapRunningFightDetailsMessage()
        { }
        
        public MapRunningFightDetailsMessage(ushort fightId, IEnumerable<Types.GameFightFighterLightInformations> attackers, IEnumerable<Types.GameFightFighterLightInformations> defenders)
        {
            this.fightId = fightId;
            this.attackers = attackers;
            this.defenders = defenders;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(fightId);
            writer.WriteShort((short)attackers.Count());
            foreach (var objectToSend in attackers)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)defenders.Count());
            foreach (var objectToSend in defenders)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightId = reader.ReadVarUShort();
            var attackersCount = reader.ReadUShort();
            var attackers_ = new Types.GameFightFighterLightInformations[attackersCount];
            for (var attackersIndex = 0; attackersIndex < attackersCount; attackersIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.GameFightFighterLightInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 attackers_[attackersIndex] = objectToAdd;
            }
            attackers = attackers_;
            var defendersCount = reader.ReadUShort();
            var defenders_ = new Types.GameFightFighterLightInformations[defendersCount];
            for (var defendersIndex = 0; defendersIndex < defendersCount; defendersIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.GameFightFighterLightInformations>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 defenders_[defendersIndex] = objectToAdd;
            }
            defenders = defenders_;
        }
    }
}