

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameActionFightTackledMessage : AbstractGameActionMessage
    {
        public const uint Id = 9014;
        public override uint MessageId => Id;
        
        public IEnumerable<double> tacklersIds;
        
        public GameActionFightTackledMessage()
        { }
        
        public GameActionFightTackledMessage(ushort actionId, double sourceId, IEnumerable<double> tacklersIds)
         : base(actionId, sourceId)
        {
            this.tacklersIds = tacklersIds;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)tacklersIds.Count());
            foreach (var objectToSend in tacklersIds)
            {
                 writer.WriteDouble(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var tacklersIdsCount = reader.ReadUShort();
            var tacklersIds_ = new double[tacklersIdsCount];
            for (var tacklersIdsIndex = 0; tacklersIdsIndex < tacklersIdsCount; tacklersIdsIndex++)
            {
                 tacklersIds_[tacklersIdsIndex] = reader.ReadDouble();
            }
            tacklersIds = tacklersIds_;
        }
    }
}