

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AllianceFactSheetInformation : AllianceInformation
    {
        public const short Id = 5455;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public int creationDate;
        public ushort nbMembers;
        public ushort nbSubarea;
        public ushort nbTaxCollectors;
        public Types.AllianceRecruitmentInformation recruitment;
        
        public AllianceFactSheetInformation()
        {
        }
        
        public AllianceFactSheetInformation(uint allianceId, string allianceTag, string allianceName, Types.SocialEmblem allianceEmblem, int creationDate, ushort nbMembers, ushort nbSubarea, ushort nbTaxCollectors, Types.AllianceRecruitmentInformation recruitment)
         : base(allianceId, allianceTag, allianceName, allianceEmblem)
        {
            this.creationDate = creationDate;
            this.nbMembers = nbMembers;
            this.nbSubarea = nbSubarea;
            this.nbTaxCollectors = nbTaxCollectors;
            this.recruitment = recruitment;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(creationDate);
            writer.WriteVarUShort(nbMembers);
            writer.WriteVarUShort(nbSubarea);
            writer.WriteVarUShort(nbTaxCollectors);
            recruitment.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            creationDate = reader.ReadInt();
            nbMembers = reader.ReadVarUShort();
            nbSubarea = reader.ReadVarUShort();
            nbTaxCollectors = reader.ReadVarUShort();
            recruitment = new Types.AllianceRecruitmentInformation();
            recruitment.Deserialize(reader);
        }
    }
}