

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class GuildFactSheetInformations : GuildInformations
    {
        public const short Id = 6548;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ulong leaderId;
        public ushort nbMembers;
        public short lastActivityDay;
        public Types.GuildRecruitmentInformation recruitment;
        public int nbPendingApply;
        
        public GuildFactSheetInformations()
        {
        }
        
        public GuildFactSheetInformations(uint guildId, string guildName, byte guildLevel, Types.SocialEmblem guildEmblem, ulong leaderId, ushort nbMembers, short lastActivityDay, Types.GuildRecruitmentInformation recruitment, int nbPendingApply)
         : base(guildId, guildName, guildLevel, guildEmblem)
        {
            this.leaderId = leaderId;
            this.nbMembers = nbMembers;
            this.lastActivityDay = lastActivityDay;
            this.recruitment = recruitment;
            this.nbPendingApply = nbPendingApply;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(leaderId);
            writer.WriteVarUShort(nbMembers);
            writer.WriteShort(lastActivityDay);
            recruitment.Serialize(writer);
            writer.WriteInt(nbPendingApply);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            leaderId = reader.ReadVarULong();
            nbMembers = reader.ReadVarUShort();
            lastActivityDay = reader.ReadShort();
            recruitment = new Types.GuildRecruitmentInformation();
            recruitment.Deserialize(reader);
            nbPendingApply = reader.ReadInt();
        }
    }
}