

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeObjectMoveToTabMessage : Message
    {
        public const uint Id = 3518;
        public override uint MessageId => Id;
        
        public uint objectUID;
        public int quantity;
        public uint tabNumber;
        
        public ExchangeObjectMoveToTabMessage()
        { }
        
        public ExchangeObjectMoveToTabMessage(uint objectUID, int quantity, uint tabNumber)
        {
            this.objectUID = objectUID;
            this.quantity = quantity;
            this.tabNumber = tabNumber;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(objectUID);
            writer.WriteVarInt(quantity);
            writer.WriteVarUInt(tabNumber);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            objectUID = reader.ReadVarUInt();
            quantity = reader.ReadVarInt();
            tabNumber = reader.ReadVarUInt();
        }
    }
}