

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeStoppedMessage : Message
    {
        public const uint Id = 2319;
        public override uint MessageId => Id;
        
        public ulong id;
        
        public ExchangeStoppedMessage()
        { }
        
        public ExchangeStoppedMessage(ulong id)
        {
            this.id = id;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(id);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            id = reader.ReadVarULong();
        }
    }
}