

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeStartOkNpcTradeMessage : Message
    {
        public const uint Id = 6250;
        public override uint MessageId => Id;
        
        public double npcId;
        public bool force;
        
        public ExchangeStartOkNpcTradeMessage()
        { }
        
        public ExchangeStartOkNpcTradeMessage(double npcId, bool force)
        {
            this.npcId = npcId;
            this.force = force;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(npcId);
            writer.WriteBoolean(force);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            npcId = reader.ReadDouble();
            force = reader.ReadBoolean();
        }
    }
}