

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeMountsPaddockRemoveMessage : Message
    {
        public const uint Id = 5043;
        public override uint MessageId => Id;
        
        public IEnumerable<int> mountsId;
        
        public ExchangeMountsPaddockRemoveMessage()
        { }
        
        public ExchangeMountsPaddockRemoveMessage(IEnumerable<int> mountsId)
        {
            this.mountsId = mountsId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)mountsId.Count());
            foreach (var objectToSend in mountsId)
            {
                 writer.WriteVarInt(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var mountsIdCount = reader.ReadUShort();
            var mountsId_ = new int[mountsIdCount];
            for (var mountsIdIndex = 0; mountsIdIndex < mountsIdCount; mountsIdIndex++)
            {
                 mountsId_[mountsIdIndex] = reader.ReadVarInt();
            }
            mountsId = mountsId_;
        }
    }
}