

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeRequestedTradeMessage : ExchangeRequestedMessage
    {
        public const uint Id = 9062;
        public override uint MessageId => Id;
        
        public ulong source;
        public ulong target;
        
        public ExchangeRequestedTradeMessage()
        { }
        
        public ExchangeRequestedTradeMessage(sbyte exchangeType, ulong source, ulong target)
         : base(exchangeType)
        {
            this.source = source;
            this.target = target;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(source);
            writer.WriteVarULong(target);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            source = reader.ReadVarULong();
            target = reader.ReadVarULong();
        }
    }
}