

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeStartOkMountMessage : ExchangeStartOkMountWithOutPaddockMessage
    {
        public const uint Id = 5527;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.MountClientData> paddockedMountsDescription;
        
        public ExchangeStartOkMountMessage()
        { }
        
        public ExchangeStartOkMountMessage(IEnumerable<Types.MountClientData> stabledMountsDescription, IEnumerable<Types.MountClientData> paddockedMountsDescription)
         : base(stabledMountsDescription)
        {
            this.paddockedMountsDescription = paddockedMountsDescription;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)paddockedMountsDescription.Count());
            foreach (var objectToSend in paddockedMountsDescription)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var paddockedMountsDescriptionCount = reader.ReadUShort();
            var paddockedMountsDescription_ = new Types.MountClientData[paddockedMountsDescriptionCount];
            for (var paddockedMountsDescriptionIndex = 0; paddockedMountsDescriptionIndex < paddockedMountsDescriptionCount; paddockedMountsDescriptionIndex++)
            {
                 var objectToAdd = new Types.MountClientData();
                 objectToAdd.Deserialize(reader);
                 paddockedMountsDescription_[paddockedMountsDescriptionIndex] = objectToAdd;
            }
            paddockedMountsDescription = paddockedMountsDescription_;
        }
    }
}