

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ExchangeStartedWithMultiTabStorageMessage : ExchangeStartedMessage
    {
        public const uint Id = 4941;
        public override uint MessageId => Id;
        
        public uint storageMaxSlot;
        public uint tabNumber;
        
        public ExchangeStartedWithMultiTabStorageMessage()
        { }
        
        public ExchangeStartedWithMultiTabStorageMessage(sbyte exchangeType, uint storageMaxSlot, uint tabNumber)
         : base(exchangeType)
        {
            this.storageMaxSlot = storageMaxSlot;
            this.tabNumber = tabNumber;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUInt(storageMaxSlot);
            writer.WriteVarUInt(tabNumber);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            storageMaxSlot = reader.ReadVarUInt();
            tabNumber = reader.ReadVarUInt();
        }
    }
}