

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class UpdateMountCharacteristicsMessage : Message
    {
        public const uint Id = 297;
        public override uint MessageId => Id;
        
        public int rideId;
        public IEnumerable<Types.UpdateMountCharacteristic> boostToUpdateList;
        
        public UpdateMountCharacteristicsMessage()
        { }
        
        public UpdateMountCharacteristicsMessage(int rideId, IEnumerable<Types.UpdateMountCharacteristic> boostToUpdateList)
        {
            this.rideId = rideId;
            this.boostToUpdateList = boostToUpdateList;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarInt(rideId);
            writer.WriteShort((short)boostToUpdateList.Count());
            foreach (var objectToSend in boostToUpdateList)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            rideId = reader.ReadVarInt();
            var boostToUpdateListCount = reader.ReadUShort();
            var boostToUpdateList_ = new Types.UpdateMountCharacteristic[boostToUpdateListCount];
            for (var boostToUpdateListIndex = 0; boostToUpdateListIndex < boostToUpdateListCount; boostToUpdateListIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.UpdateMountCharacteristic>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 boostToUpdateList_[boostToUpdateListIndex] = objectToAdd;
            }
            boostToUpdateList = boostToUpdateList_;
        }
    }
}