

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildPlayerApplicationInformationMessage : GuildPlayerApplicationAbstractMessage
    {
        public const uint Id = 7755;
        public override uint MessageId => Id;
        
        public Types.GuildInformations guildInformation;
        public Types.SocialApplicationInformation apply;
        
        public GuildPlayerApplicationInformationMessage()
        { }
        
        public GuildPlayerApplicationInformationMessage(Types.GuildInformations guildInformation, Types.SocialApplicationInformation apply)
        {
            this.guildInformation = guildInformation;
            this.apply = apply;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            guildInformation.Serialize(writer);
            apply.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            guildInformation = new Types.GuildInformations();
            guildInformation.Deserialize(reader);
            apply = new Types.SocialApplicationInformation();
            apply.Deserialize(reader);
        }
    }
}