

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildPlayerNoApplicationInformationMessage : GuildPlayerApplicationAbstractMessage
    {
        public const uint Id = 6444;
        public override uint MessageId => Id;
        
        
        public GuildPlayerNoApplicationInformationMessage()
        { }
        
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
        }
    }
}