

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GuildApplicationDeletedMessage : Message
    {
        public const uint Id = 5082;
        public override uint MessageId => Id;
        
        public bool deleted;
        
        public GuildApplicationDeletedMessage()
        { }
        
        public GuildApplicationDeletedMessage(bool deleted)
        {
            this.deleted = deleted;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(deleted);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            deleted = reader.ReadBoolean();
        }
    }
}