

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class KickHavenBagRequestMessage : Message
    {
        public const uint Id = 3366;
        public override uint MessageId => Id;
        
        public ulong guestId;
        
        public KickHavenBagRequestMessage()
        { }
        
        public KickHavenBagRequestMessage(ulong guestId)
        {
            this.guestId = guestId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(guestId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            guestId = reader.ReadVarULong();
        }
    }
}