

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class BidExchangerObjectInfo
    {
        public const short Id = 8930;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public uint objectUID;
        public uint objectGID;
        public int objectType;
        public IEnumerable<Types.ObjectEffect> effects;
        public IEnumerable<ulong> prices;
        
        public BidExchangerObjectInfo()
        {
        }
        
        public BidExchangerObjectInfo(uint objectUID, uint objectGID, int objectType, IEnumerable<Types.ObjectEffect> effects, IEnumerable<ulong> prices)
        {
            this.objectUID = objectUID;
            this.objectGID = objectGID;
            this.objectType = objectType;
            this.effects = effects;
            this.prices = prices;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(objectUID);
            writer.WriteVarUInt(objectGID);
            writer.WriteInt(objectType);
            writer.WriteShort((short)effects.Count());
            foreach (var objectToSend in effects)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
            writer.WriteShort((short)prices.Count());
            foreach (var objectToSend in prices)
            {
                 writer.WriteVarULong(objectToSend);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            objectUID = reader.ReadVarUInt();
            objectGID = reader.ReadVarUInt();
            objectType = reader.ReadInt();
            var effectsCount = reader.ReadUShort();
            var effects_ = new Types.ObjectEffect[effectsCount];
            for (var effectsIndex = 0; effectsIndex < effectsCount; effectsIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.ObjectEffect>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 effects_[effectsIndex] = objectToAdd;
            }
            effects = effects_;
            var pricesCount = reader.ReadUShort();
            var prices_ = new ulong[pricesCount];
            for (var pricesIndex = 0; pricesIndex < pricesCount; pricesIndex++)
            {
                 prices_[pricesIndex] = reader.ReadVarULong();
            }
            prices = prices_;
        }
    }
}