

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ObjectItemQuantityPriceDateEffects : ObjectItemGenericQuantity
    {
        public const short Id = 8474;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ulong price;
        public Types.ObjectEffects effects;
        public int date;
        
        public ObjectItemQuantityPriceDateEffects()
        {
        }
        
        public ObjectItemQuantityPriceDateEffects(uint objectGID, uint quantity, ulong price, Types.ObjectEffects effects, int date)
         : base(objectGID, quantity)
        {
            this.price = price;
            this.effects = effects;
            this.date = date;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(price);
            effects.Serialize(writer);
            writer.WriteInt(date);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            price = reader.ReadVarULong();
            effects = new Types.ObjectEffects();
            effects.Deserialize(reader);
            date = reader.ReadInt();
        }
    }
}