using System;
using System.Collections.Generic;
using System.Linq;
using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.Relator;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Mounts;
using Stump.Server.WorldServer.Game.Maps;

namespace Stump.Server.WorldServer.Database.Mounts
{
    public class MountRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_mounts";

        public static string FindById = "SELECT * FROM characters_mounts WHERE Id={0}";

        public static string FindByOwner = "SELECT * FROM characters_mounts WHERE OwnerId = {0}";

        public static string FindByOwnerStabled = "SELECT * FROM characters_mounts WHERE OwnerId = {0} AND IsInStable = 1 AND PaddockId IS NOT NULL";

        public static string FindByOwnerPublicPaddocked = "" +
            "SELECT characters_mounts.*, " +
            "world_maps_paddock.IsPublic, " +
            "world_maps_paddock.GuildId, " +
            "world_maps_paddock.MapId, " +
            "world_maps_paddock.MaxOutdoorMount, " +
            "world_maps_paddock.MaxItems, " +
            "world_maps_paddock.ItemsCSV, " +
            "world_maps_paddock.OnSale," +
            "world_maps_paddock.Locked, " +
            "world_maps_paddock.Price, " +
            "world_maps_paddock.Abandonned " +
            "FROM characters_mounts " +
            "INNER JOIN world_maps_paddock ON world_maps_paddock.Id = characters_mounts.PaddockId WHERE characters_mounts.OwnerId = {0} AND characters_mounts.PaddockId IS NOT NULL AND characters_mounts.IsInStable = 0 AND world_maps_paddock.GuildId = -1";

        public static string FetchByPaddockId = "SELECT * FROM characters_mounts WHERE PaddockId={0} AND IsInStable=0";

        public static string DeleteStoredSince = "DELETE FROM characters_mounts WHERE StoredSince IS NOT NULL AND StoredSince < \"{0}\"";
    }

    [TableName("characters_mounts")]
    public class MountRecord : AutoAssignedRecord<MountRecord>, IJoined, IAutoGeneratedRecord
    {
        #region >> Properties Privates
        private Map m_map;
        private List<int> m_ancestors;
        private List<int> m_behaviors;
        private MountTemplate m_template;
        private string m_ancestorsCSV = string.Empty;
        private string m_behaviorsCSV = string.Empty;

        private int? ownerId;
        private string ownerName;
        private string name;
        private DateTime fecondationDate;
        private Boolean isFecondationReady;
        private Boolean sex;
        private int templateId;
        private long experience;
        private sbyte givenExperience;
        private int stamina;
        private int maturity;
        private int energy;
        private int serenity;
        private int love;
        private int tiredness;
        private DateTime? storedSince;
        private int? paddockId;
        private long? paddockMapId;
        private int paddockCellId;
        private int paddockMountDirection;
        private int reproductionCount;
        private Boolean isInStable;
        private Boolean isEquipped;
        #endregion

        #region >> Properties Public
        [Index]
        public int? OwnerId
        {
            get { return ownerId; }
            set
            {
                ownerId = value;
            }
        }

        [NullString]
        public string OwnerName
        {
            get { return ownerName; }
            set
            {
                ownerName = value;
            }
        }

        public String Name
        {
            get { return name; }
            set
            {
                name = value;
            }
        }

        public DateTime FecondationDate
        {
            get { return fecondationDate; }
            set
            {
                fecondationDate = value;
            }
        }

        public Boolean IsFecondationReady
        {
            get { return isFecondationReady; }
            set
            {
                isFecondationReady = value;
            }
        }

        public Boolean Sex
        {
            get { return sex; }
            set
            {
                sex = value;
            }
        }

        public int TemplateId
        {
            get { return templateId; }
            set
            {
                templateId = value;
            }
        }

        [Ignore]
        public MountTemplate Template => m_template ?? (m_template = MountManager.Instance.GetTemplate(TemplateId));

        public long Experience
        {
            get { return experience; }
            set
            {
                experience = value;
            }
        }

        public sbyte GivenExperience
        {
            get { return givenExperience; }
            set
            {
                givenExperience = value;
            }
        }

        public int Stamina
        {
            get { return stamina; }
            set
            {
                stamina = value;
            }
        }

        public int Maturity
        {
            get { return maturity; }
            set
            {
                maturity = value;
            }
        }

        public int Energy
        {
            get { return energy; }
            set
            {
                energy = value;
            }
        }

        public int Serenity
        {
            get { return serenity; }
            set
            {
                serenity = value;
            }
        }

        public int Love
        {
            get { return love; }
            set
            {
                love = value;
            }
        }

        public int Tiredness
        {
            get { return tiredness; }
            set
            {
                tiredness = value;
            }
        }

        public string BehaviorsCSV
        {
            get { return m_behaviorsCSV; }
            set
            {
                m_behaviorsCSV = value;
                m_behaviors = BehaviorsCSV.FromCSV<int>(",").ToList();
            }
        }

        [Ignore]
        public List<int> Behaviors
        {
            get
            {
                return m_behaviors ?? (m_behaviors = BehaviorsCSV.FromCSV<int>(",").ToList());
            }
            set
            {
                m_behaviors = value;
                BehaviorsCSV = value.ToCSV(",");
            }
        }

        public string AncestorsCSV
        {
            get { return m_ancestorsCSV; }
            set
            {
                m_ancestorsCSV = value;
                m_ancestors = BehaviorsCSV.FromCSV<int>(",").ToList();
            }
        }

        [Ignore]
        public List<int> Ancestors
        {
            get
            {
                return AncestorsCSV.FromCSV<int>(",").ToList();
            }
            set
            {
                m_ancestors = value;
                AncestorsCSV = value.ToCSV(",");
            }
        }

        public DateTime? StoredSince
        {
            get { return storedSince; }
            set
            {
                storedSince = value;
            }
        }

        [Index]
        public int? PaddockId
        {
            get { return paddockId; }
            set
            {
                paddockId = value;
            }
        }

        public long? PaddockMapId
        {
            get { return paddockMapId; }
            set
            {
                paddockMapId = value;
            }
        }

        public int PaddockCellId
        {
            get { return paddockCellId; }
            set
            {
                paddockCellId = value;
            }
        }

        public int PaddockMountDirection
        {
            get { return paddockMountDirection; }
            set
            {
                paddockMountDirection = value;
            }
        }

        public int ReproductionCount
        {
            get { return reproductionCount; }
            set
            {
                reproductionCount = value;
            }
        }

        public bool IsInStable
        {
            get { return isInStable; }
            set
            {
                isInStable = value;
            }
        }

        public bool IsEquipped
        {
            get { return isEquipped; }
            set
            {
                isEquipped = value;
            }
        }

        [Ignore]
        public bool IsDirty { get; set; }

        [Ignore]
        public Map Map
        {
            get
            {
                if (!PaddockMapId.HasValue)
                    return null;

                return m_map ?? (m_map = Game.World.Instance.GetMap(PaddockMapId.Value));
            }
            set
            {
                m_map = value;

                if (value == null)
                    PaddockMapId = null;
                else
                    PaddockMapId = value.Id;
            }
        }
        #endregion

        int IJoined.JoinedId => PaddockId ?? -1;

        public override void BeforeSave(bool insert)
        {
            BehaviorsCSV = Behaviors.ToCSV(",");
            base.BeforeSave(insert);
        }
    }
}