using System.Collections.Generic;
using System.Linq;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.Relator;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Actors.Look;
using Stump.Server.WorldServer.Game.Effects;
using Stump.Server.WorldServer.Game.Effects.Instances;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Mounts
{
    public class MountTemplateRelator : OneToManyRelator<MountTemplate, MountBonus>
    {
        public static string FetchQueryAll = "SELECT * FROM mounts_templates";

        public static string FetchQuery = "SELECT * FROM mounts_templates LEFT JOIN mounts_bonus ON mounts_templates.Id = mounts_bonus.MountTemplateId";
    }

    [TableName("mounts_templates")]
    [D2OClass("Mount", "com.ankamagames.dofus.datacenter.mounts")]
    public sealed class MountTemplate : IAssignedByD2O, IAutoGeneratedRecord, IOneToManyRecord1<MountBonus>
    {
        public const int DEFAULT_SCROLL_ITEM = (int)ItemIdEnum.CERTIFICAT_DE_MONTURE_7806;

        private string m_name;
        private string m_lookAsString;
        private byte[] m_effectsBin;
        private List<EffectDice> m_effects;
        private ActorLook m_entityLook;
        private ItemTemplate m_CertificateItem;

        [PrimaryKey("Id", autoIncrement: false)]
        public int Id { get; set; }

        int IJoined.JoinedId => Id;

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
            set { m_name = value is null ? string.Empty : value; }
        }

        public uint NameId { get; set; }

        public string Look
        {
            get
            {
                if (EntityLook == null)
                    return string.Empty;

                if (string.IsNullOrEmpty(m_lookAsString))
                    m_lookAsString = EntityLook.ToString();

                return m_lookAsString;
            }
            set
            {
                m_lookAsString = value;

                if (!string.IsNullOrEmpty(value) && value != "null")
                    m_entityLook = ActorLook.Parse(m_lookAsString);
                else
                    m_entityLook = null;
            }
        }

        public int PodsBase { get; set; }

        public int PodsPerLevel { get; set; }

        public int EnergyBase { get; set; }

        public int EnergyPerLevel { get; set; }

        public int MaturityMax { get; set; }

        public int FecondationTime { get; set; }

        public sbyte LearnCoefficient { get; set; }

        public int FamilyId { get; set; }

        public uint CertificateId { get; set; }

        public byte[] EffectsBin
        {
            get { return m_effectsBin; }
            set
            {
                m_effectsBin = value;
                m_effects = EffectManager.Instance.DeserializeEffects(EffectsBin).Cast<EffectDice>().ToList();
            }
        }

        [Ignore]
        public List<EffectDice> Effects
        {
            get
            {
                return m_effects ?? (m_effects = EffectManager.Instance.DeserializeEffects(EffectsBin).Cast<EffectDice>().ToList());
            }
            set
            {
                m_effects = value;
            }
        }

        [Ignore]
        public ActorLook EntityLook
        {
            get { return m_entityLook; }
            set
            {
                m_entityLook = value;

                if (value != null)
                    m_lookAsString = value.ToString();
            }
        }

        [Ignore]
        public List<MountBonus> Bonuses { get; set; } = new List<MountBonus>();

        List<MountBonus> IOneToManyRecord1<MountBonus>.ManyProperty1 => Bonuses;

        public ItemTemplate certificateItem => m_CertificateItem ?? (m_CertificateItem = ItemManager.Instance.TryGetTemplate(CertificateId == 0 ? DEFAULT_SCROLL_ITEM : (int)CertificateId));

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var mount = (Mount)d2oObject;
            Id = (int)mount.id;
            Name = "";
            NameId = mount.nameId;
            Look = mount.look;
            FamilyId = (int)mount.FamilyId;
            CertificateId = mount.CertificateId;
            m_effectsBin = EffectManager.Instance.SerializeEffects(mount.effects);
        }

        #endregion
    }
}