

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AccountPinValidResponseMessage : Message
    {
        public const uint Id = 304;
        public override uint MessageId => Id;
        
        public bool success;
        
        public AccountPinValidResponseMessage()
        { }
        
        public AccountPinValidResponseMessage(bool success)
        {
            this.success = success;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(success);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            success = reader.ReadBoolean();
        }
    }
}