

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AccountPinValidMessage : Message
    {
        public const uint Id = 303;
        public override uint MessageId => Id;
        
        public string pin;
        public bool session;
        
        public AccountPinValidMessage()
        { }
        
        public AccountPinValidMessage(string pin, bool session)
        {
            this.pin = pin;
            this.session = session;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(pin);
            writer.WriteBoolean(session);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            pin = reader.ReadUTF();
            session = reader.ReadBoolean();
        }
    }
}