

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AuraEmoteSelectMessage : Message
    {
        public const uint Id = 9992;
        public override uint MessageId => Id;
        
        public uint auraId;
        
        public AuraEmoteSelectMessage()
        { }
        
        public AuraEmoteSelectMessage(uint auraId)
        {
            this.auraId = auraId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUInt(auraId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            auraId = reader.ReadUInt();
        }
    }
}