

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PocketButtonUseMessage : Message
    {
        public const uint Id = 394;
        public override uint MessageId => Id;
        
        public uint buttonId;
        
        public PocketButtonUseMessage()
        { }
        
        public PocketButtonUseMessage(uint buttonId)
        {
            this.buttonId = buttonId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUInt(buttonId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            buttonId = reader.ReadUInt();
        }
    }
}