

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("ServerSeason", "com.ankamagames.dofus.datacenter.seasons")]
    [Serializable]
    public class ServerSeason : Season
    {
        public const String MODULE = "ServerSeasons";
    }
}