

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AccountHouseMessage : Message
    {
        public const uint Id = 6567;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.AccountHouseInformations> houses;
        
        public AccountHouseMessage()
        { }
        
        public AccountHouseMessage(IEnumerable<Types.AccountHouseInformations> houses)
        {
            this.houses = houses;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)houses.Count());
            foreach (var objectToSend in houses)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var housesCount = reader.ReadUShort();
            var houses_ = new Types.AccountHouseInformations[housesCount];
            for (var housesIndex = 0; housesIndex < housesCount; housesIndex++)
            {
                 var objectToAdd = new Types.AccountHouseInformations();
                 objectToAdd.Deserialize(reader);
                 houses_[housesIndex] = objectToAdd;
            }
            houses = houses_;
        }
    }
}