

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HouseToSellFilterMessage : Message
    {
        public const uint Id = 7368;
        public override uint MessageId => Id;
        
        public int areaId;
        public sbyte atLeastNbRoom;
        public sbyte atLeastNbChest;
        public ushort skillRequested;
        public ulong maxPrice;
        public sbyte orderBy;
        
        public HouseToSellFilterMessage()
        { }
        
        public HouseToSellFilterMessage(int areaId, sbyte atLeastNbRoom, sbyte atLeastNbChest, ushort skillRequested, ulong maxPrice, sbyte orderBy)
        {
            this.areaId = areaId;
            this.atLeastNbRoom = atLeastNbRoom;
            this.atLeastNbChest = atLeastNbChest;
            this.skillRequested = skillRequested;
            this.maxPrice = maxPrice;
            this.orderBy = orderBy;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteInt(areaId);
            writer.WriteSByte(atLeastNbRoom);
            writer.WriteSByte(atLeastNbChest);
            writer.WriteVarUShort(skillRequested);
            writer.WriteVarULong(maxPrice);
            writer.WriteSByte(orderBy);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            areaId = reader.ReadInt();
            atLeastNbRoom = reader.ReadSByte();
            atLeastNbChest = reader.ReadSByte();
            skillRequested = reader.ReadVarUShort();
            maxPrice = reader.ReadVarULong();
            orderBy = reader.ReadSByte();
        }
    }
}