

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HouseToSellListMessage : Message
    {
        public const uint Id = 4751;
        public override uint MessageId => Id;
        
        public ushort pageIndex;
        public ushort totalPage;
        public IEnumerable<Types.HouseInformationsForSell> houseList;
        
        public HouseToSellListMessage()
        { }
        
        public HouseToSellListMessage(ushort pageIndex, ushort totalPage, IEnumerable<Types.HouseInformationsForSell> houseList)
        {
            this.pageIndex = pageIndex;
            this.totalPage = totalPage;
            this.houseList = houseList;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(pageIndex);
            writer.WriteVarUShort(totalPage);
            writer.WriteShort((short)houseList.Count());
            foreach (var objectToSend in houseList)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            pageIndex = reader.ReadVarUShort();
            totalPage = reader.ReadVarUShort();
            var houseListCount = reader.ReadUShort();
            var houseList_ = new Types.HouseInformationsForSell[houseListCount];
            for (var houseListIndex = 0; houseListIndex < houseListCount; houseListIndex++)
            {
                 var objectToAdd = new Types.HouseInformationsForSell();
                 objectToAdd.Deserialize(reader);
                 houseList_[houseListIndex] = objectToAdd;
            }
            houseList = houseList_;
        }
    }
}