using Stump.ORM;
using Stump.Server.WorldServer.Database.I18n;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using System;

namespace Stump.Server.WorldServer.Database.Npcs
{
    public class FeatureTemplatesRelator
    {
        public static string FetchQuery = "SELECT * FROM feature_descriptions";
    }

    [TableName("feature_descriptions")]
    [D2OClass("FeatureDescriptions", "com.ankamagames.dofus.datacenter.npcs")]
    public class FeatureTemplatesRecord : IAutoGeneratedRecord
    {
        private string m_name;
        private string m_description;

        [PrimaryKey("Id", false)]
        public int Id { get; set; }

        public uint NameId { get; set; }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
            set { m_name = value; }
        }

        public uint DescriptionId { get; set; }

        public string Description
        {
            get { return m_description ?? (m_description = TextManager.Instance.GetText(DescriptionId)); }
            set { m_description = value; }
        }

        public int Priority { get; set; }

        public int ParentId { get; set; }

        public string Children { get; set; }

        public string Criterion { get; set; }

        public Boolean Active { get; set; }
    }
}