using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Presets;
using System.Linq;

namespace Stump.Server.WorldServer.Database.Presets
{
    public class ItemsPresetRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_presets_items";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByPresetId = "SELECT * FROM characters_presets_items WHERE PresetId={0}";
        public static string FetchByObjectId = "SELECT * FROM characters_presets_items WHERE objectId={0}";
    }

    [TableName("characters_presets_items")]
    public class ItemsPresetRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        [Index]
        public int OwnerId
        {
            get;
            set;
        }

        public int PresetId
        {
            get;
            set;
        }

        public uint objectId
        {
            get;
            set;
        }

        public short Position
        {
            get;
            set;
        }
        public uint ObjGid
        {
            get;
            set;
        }
        public uint ObjUid
        {
            get;
            set;
        }
        
        [Ignore]
        public ItemForPreset Item
        {
            get
            {
                return new ItemForPreset(Position, ObjGid, ObjUid);
            }
            set
            {
                Position = value.position;
                ObjGid = value.objGid;
                ObjUid = value.objUid;
            }
        }
    }
}