using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Presets;
using System.Linq;

namespace Stump.Server.WorldServer.Database.Presets
{
    public class StatsPresetsRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_presets_stats";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByPresetId = "SELECT * FROM characters_presets_stats WHERE PresetId={0}";
        public static string FetchByObjectId = "SELECT * FROM characters_presets_stats WHERE objectId={0}";
    }

    [TableName("characters_presets_stats")]
    public class StatsPresetsRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        [Index]
        public int OwnerId
        {
            get;
            set;
        }

        public int PresetId
        {
            get;
            set;
        }

        public short objectId
        {
            get;
            set;
        }

        public byte[] StatsBin
        {
            get;
            set;
        }

        [Ignore]
        public FullStatsPreset Stats
        {
            get
            {
                return PresetsManager.Instance.DeserializeFullStatsPreset(StatsBin);
            }
            set
            {
                StatsBin = PresetsManager.Instance.SerializeFullStatsPreset(value);
            }
        }
    }
}