

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AlliancePlayerApplicationInformationMessage : AlliancePlayerApplicationAbstractMessage
    {
        public const uint Id = 9416;
        public override uint MessageId => Id;
        
        public Types.AllianceInformation allianceInformation;
        public Types.SocialApplicationInformation apply;
        
        public AlliancePlayerApplicationInformationMessage()
        { }
        
        public AlliancePlayerApplicationInformationMessage(Types.AllianceInformation allianceInformation, Types.SocialApplicationInformation apply)
        {
            this.allianceInformation = allianceInformation;
            this.apply = apply;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            allianceInformation.Serialize(writer);
            apply.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            allianceInformation = new Types.AllianceInformation();
            allianceInformation.Deserialize(reader);
            apply = new Types.SocialApplicationInformation();
            apply.Deserialize(reader);
        }
    }
}