

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AllianceInsiderPrismInformation : PrismInformation
    {
        public const short Id = 6387;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public Types.ObjectItem moduleObject;
        public int moduleType;
        public Types.ObjectItem cristalObject;
        public int cristalType;
        public int cristalNumberLeft;
        
        public AllianceInsiderPrismInformation()
        {
        }
        
        public AllianceInsiderPrismInformation(sbyte state, int placementDate, uint nuggetsCount, int durability, double nextEvolutionDate, Types.ObjectItem moduleObject, int moduleType, Types.ObjectItem cristalObject, int cristalType, int cristalNumberLeft)
         : base(state, placementDate, nuggetsCount, durability, nextEvolutionDate)
        {
            this.moduleObject = moduleObject;
            this.moduleType = moduleType;
            this.cristalObject = cristalObject;
            this.cristalType = cristalType;
            this.cristalNumberLeft = cristalNumberLeft;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            moduleObject.Serialize(writer);
            writer.WriteInt(moduleType);
            cristalObject.Serialize(writer);
            writer.WriteInt(cristalType);
            writer.WriteInt(cristalNumberLeft);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            moduleObject = new Types.ObjectItem();
            moduleObject.Deserialize(reader);
            moduleType = reader.ReadInt();
            cristalObject = new Types.ObjectItem();
            cristalObject.Deserialize(reader);
            cristalType = reader.ReadInt();
            cristalNumberLeft = reader.ReadInt();
        }
    }
}