

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ObjectEffectDate : ObjectEffect
    {
        public const short Id = 3111;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ushort year;
        public sbyte month;
        public sbyte day;
        public sbyte hour;
        public sbyte minute;
        
        public ObjectEffectDate()
        {
        }
        
        public ObjectEffectDate(ushort actionId, ushort year, sbyte month, sbyte day, sbyte hour, sbyte minute)
         : base(actionId)
        {
            this.year = year;
            this.month = month;
            this.day = day;
            this.hour = hour;
            this.minute = minute;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUShort(year);
            writer.WriteSByte(month);
            writer.WriteSByte(day);
            writer.WriteSByte(hour);
            writer.WriteSByte(minute);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            year = reader.ReadVarUShort();
            month = reader.ReadSByte();
            day = reader.ReadSByte();
            hour = reader.ReadSByte();
            minute = reader.ReadSByte();
        }
    }
}