

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("GuildRight", "com.ankamagames.dofus.datacenter.guild")]
    [Serializable]
    public class GuildRight : SocialRight
    {
        public const String MODULE = "GuildRights";
    }
}