

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AcquaintanceOnlineInformation : AcquaintanceInformation
    {
        public const short Id = 6565;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public ulong playerId;
        public string playerName;
        public ushort moodSmileyId;
        public Types.PlayerStatus status;
        
        public AcquaintanceOnlineInformation()
        {
        }
        
        public AcquaintanceOnlineInformation(int accountId, Types.AccountTagInformation accountTag, sbyte playerState, ulong playerId, string playerName, ushort moodSmileyId, Types.PlayerStatus status)
         : base(accountId, accountTag, playerState)
        {
            this.playerId = playerId;
            this.playerName = playerName;
            this.moodSmileyId = moodSmileyId;
            this.status = status;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(playerId);
            writer.WriteUTF(playerName);
            writer.WriteVarUShort(moodSmileyId);
            writer.WriteShort(status.TypeId);
            status.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            playerId = reader.ReadVarULong();
            playerName = reader.ReadUTF();
            moodSmileyId = reader.ReadVarUShort();
            status = Types.ProtocolTypeManager.GetInstance<Types.PlayerStatus>(reader.ReadShort());
            status.Deserialize(reader);
        }
    }
}