

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class SequenceEndMessage : Message
    {
        public const uint Id = 2945;
        public override uint MessageId => Id;
        
        public ushort actionId;
        public double authorId;
        public sbyte sequenceType;
        
        public SequenceEndMessage()
        { }
        
        public SequenceEndMessage(ushort actionId, double authorId, sbyte sequenceType)
        {
            this.actionId = actionId;
            this.authorId = authorId;
            this.sequenceType = sequenceType;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(actionId);
            writer.WriteDouble(authorId);
            writer.WriteSByte(sequenceType);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            actionId = reader.ReadVarUShort();
            authorId = reader.ReadDouble();
            sequenceType = reader.ReadSByte();
        }
    }
}