//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("Collectable", "com.ankamagames.dofus.datacenter.collection")]
    [Serializable]
    public class Collectable : IDataObject, IIndexedData
    {
        public const String MODULE = "Collectables";
        public int entityId;
        public String name;
        public int typeId;
        public int gfxId;
        public int order;
        public int rarity;
        int IIndexedData.Id
        {
            get { return (int)entityId; }
        }
        [D2OIgnore]
        public int EntityId
        {
            get { return this.entityId; }
            set { this.entityId = value; }
        }
        [D2OIgnore]
        public String Name
        {
            get { return this.name; }
            set { this.name = value; }
        }
        [D2OIgnore]
        public int TypeId
        {
            get { return this.typeId; }
            set { this.typeId = value; }
        }
        [D2OIgnore]
        public int GfxId
        {
            get { return this.gfxId; }
            set { this.gfxId = value; }
        }
        [D2OIgnore]
        public int Order
        {
            get { return this.order; }
            set { this.order = value; }
        }
        [D2OIgnore]
        public int Rarity
        {
            get { return this.rarity; }
            set { this.rarity = value; }
        }
    }
}