//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("Collection", "com.ankamagames.dofus.datacenter.collection")]
    [Serializable]
    public class Collection : IDataObject, IIndexedData
    {
        public const String MODULE = "Collections";
        public int typeId;
        public String name;
        public String criterion;
        public List<Collectable> collectables;
        int IIndexedData.Id
        {
            get { return typeId; }
        }
        [D2OIgnore]
        public int TypeId
        {
            get { return this.typeId; }
            set { this.typeId = value; }
        }
        [D2OIgnore]
        public String Name
        {
            get { return this.name; }
            set { this.name = value; }
        }
        [D2OIgnore]
        public String Criterion
        {
            get { return this.criterion; }
            set { this.criterion = value; }
        }
        [D2OIgnore]
        public List<Collectable> Collectables
        {
            get { return this.collectables; }
            set { this.collectables = value; }
        }
    }
}