using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.MapsReset
{
    public class MapsResetModalTableRelator
    {
        public static string FetchQuery = "SELECT * FROM maps_reset";
    }

    [TableName("maps_reset")]
    class MapsResetModal : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public int MapId
        {
            get;
            set;
        }

    }
}
