

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class StatedElement
    {
        public const short Id = 2912;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public int elementId;
        public ushort elementCellId;
        public uint elementState;
        public bool onCurrentMap;
        
        public StatedElement()
        {
        }
        
        public StatedElement(int elementId, ushort elementCellId, uint elementState, bool onCurrentMap)
        {
            this.elementId = elementId;
            this.elementCellId = elementCellId;
            this.elementState = elementState;
            this.onCurrentMap = onCurrentMap;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteInt(elementId);
            writer.WriteVarUShort(elementCellId);
            writer.WriteVarUInt(elementState);
            writer.WriteBoolean(onCurrentMap);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            elementId = reader.ReadInt();
            elementCellId = reader.ReadVarUShort();
            elementState = reader.ReadVarUInt();
            onCurrentMap = reader.ReadBoolean();
        }
    }
}