

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HaapiBufferListMessage : Message
    {
        public const uint Id = 8253;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.BufferInformation> buffers;
        
        public HaapiBufferListMessage()
        { }
        
        public HaapiBufferListMessage(IEnumerable<Types.BufferInformation> buffers)
        {
            this.buffers = buffers;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)buffers.Count());
            foreach (var objectToSend in buffers)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var buffersCount = reader.ReadUShort();
            var buffers_ = new Types.BufferInformation[buffersCount];
            for (var buffersIndex = 0; buffersIndex < buffersCount; buffersIndex++)
            {
                 var objectToAdd = new Types.BufferInformation();
                 objectToAdd.Deserialize(reader);
                 buffers_[buffersIndex] = objectToAdd;
            }
            buffers = buffers_;
        }
    }
}