

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HaapiBuyValidationMessage : HaapiValidationMessage
    {
        public const uint Id = 4326;
        public override uint MessageId => Id;
        
        public ulong amount;
        public string email;
        
        public HaapiBuyValidationMessage()
        { }
        
        public HaapiBuyValidationMessage(sbyte action, sbyte code, ulong amount, string email)
         : base(action, code)
        {
            this.amount = amount;
            this.email = email;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(amount);
            writer.WriteUTF(email);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            amount = reader.ReadVarULong();
            email = reader.ReadUTF();
        }
    }
}