

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class HaapiSessionMessage : Message
    {
        public const uint Id = 407;
        public override uint MessageId => Id;
        
        public string key;
        public sbyte type;
        
        public HaapiSessionMessage()
        { }
        
        public HaapiSessionMessage(string key, sbyte type)
        {
            this.key = key;
            this.type = type;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(key);
            writer.WriteSByte(type);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            key = reader.ReadUTF();
            type = reader.ReadSByte();
        }
    }
}