

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PurchasableDialogMessage : Message
    {
        public const uint Id = 9556;
        public override uint MessageId => Id;
        
        public bool buyOrSell;
        public bool secondHand;
        public double purchasableId;
        public int purchasableInstanceId;
        public ulong price;
        
        public PurchasableDialogMessage()
        { }
        
        public PurchasableDialogMessage(bool buyOrSell, bool secondHand, double purchasableId, int purchasableInstanceId, ulong price)
        {
            this.buyOrSell = buyOrSell;
            this.secondHand = secondHand;
            this.purchasableId = purchasableId;
            this.purchasableInstanceId = purchasableInstanceId;
            this.price = price;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, buyOrSell);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, secondHand);
            writer.WriteByte(flag1);
            writer.WriteDouble(purchasableId);
            writer.WriteInt(purchasableInstanceId);
            writer.WriteVarULong(price);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            byte flag1 = reader.ReadByte();
            buyOrSell = BooleanByteWrapper.GetFlag(flag1, 0);
            secondHand = BooleanByteWrapper.GetFlag(flag1, 1);
            purchasableId = reader.ReadDouble();
            purchasableInstanceId = reader.ReadInt();
            price = reader.ReadVarULong();
        }
    }
}