

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class KnownZaapListMessage : Message
    {
        public const uint Id = 3175;
        public override uint MessageId => Id;
        
        public IEnumerable<double> destinations;
        
        public KnownZaapListMessage()
        { }
        
        public KnownZaapListMessage(IEnumerable<double> destinations)
        {
            this.destinations = destinations;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)destinations.Count());
            foreach (var objectToSend in destinations)
            {
                 writer.WriteDouble(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var destinationsCount = reader.ReadUShort();
            var destinations_ = new double[destinationsCount];
            for (var destinationsIndex = 0; destinationsIndex < destinationsCount; destinationsIndex++)
            {
                 destinations_[destinationsIndex] = reader.ReadDouble();
            }
            destinations = destinations_;
        }
    }
}