

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ZaapRespawnUpdatedMessage : Message
    {
        public const uint Id = 3172;
        public override uint MessageId => Id;
        
        public double mapId;
        
        public ZaapRespawnUpdatedMessage()
        { }
        
        public ZaapRespawnUpdatedMessage(double mapId)
        {
            this.mapId = mapId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(mapId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            mapId = reader.ReadDouble();
        }
    }
}