

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameRolePlayArenaLeagueRewardsMessage : Message
    {
        public const uint Id = 5646;
        public override uint MessageId => Id;
        
        public ushort seasonId;
        public ushort leagueId;
        public int ladderPosition;
        public bool endSeasonReward;
        
        public GameRolePlayArenaLeagueRewardsMessage()
        { }
        
        public GameRolePlayArenaLeagueRewardsMessage(ushort seasonId, ushort leagueId, int ladderPosition, bool endSeasonReward)
        {
            this.seasonId = seasonId;
            this.leagueId = leagueId;
            this.ladderPosition = ladderPosition;
            this.endSeasonReward = endSeasonReward;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(seasonId);
            writer.WriteVarUShort(leagueId);
            writer.WriteInt(ladderPosition);
            writer.WriteBoolean(endSeasonReward);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            seasonId = reader.ReadVarUShort();
            leagueId = reader.ReadVarUShort();
            ladderPosition = reader.ReadInt();
            endSeasonReward = reader.ReadBoolean();
        }
    }
}