

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameRolePlayArenaFightPropositionMessage : Message
    {
        public const uint Id = 3773;
        public override uint MessageId => Id;
        
        public ushort fightId;
        public IEnumerable<double> alliesId;
        public ushort duration;
        
        public GameRolePlayArenaFightPropositionMessage()
        { }
        
        public GameRolePlayArenaFightPropositionMessage(ushort fightId, IEnumerable<double> alliesId, ushort duration)
        {
            this.fightId = fightId;
            this.alliesId = alliesId;
            this.duration = duration;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(fightId);
            writer.WriteShort((short)alliesId.Count());
            foreach (var objectToSend in alliesId)
            {
                 writer.WriteDouble(objectToSend);
            }
            writer.WriteVarUShort(duration);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightId = reader.ReadVarUShort();
            var alliesIdCount = reader.ReadUShort();
            var alliesId_ = new double[alliesIdCount];
            for (var alliesIdIndex = 0; alliesIdIndex < alliesIdCount; alliesIdIndex++)
            {
                 alliesId_[alliesIdIndex] = reader.ReadDouble();
            }
            alliesId = alliesId_;
            duration = reader.ReadVarUShort();
        }
    }
}