

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class CharacterHardcoreOrEpicInformations : CharacterBaseInformations
    {
        public const short Id = 969;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public sbyte deathState;
        public ushort deathCount;
        public ushort deathMaxLevel;
        
        public CharacterHardcoreOrEpicInformations()
        {
        }
        
        public CharacterHardcoreOrEpicInformations(ulong id, string name, ushort level, Types.EntityLook entityLook, sbyte breed, bool sex, short prestige, sbyte deathState, ushort deathCount, ushort deathMaxLevel)
         : base(id, name, level, entityLook, breed, sex, prestige)
        {
            this.deathState = deathState;
            this.deathCount = deathCount;
            this.deathMaxLevel = deathMaxLevel;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(deathState);
            writer.WriteVarUShort(deathCount);
            writer.WriteVarUShort(deathMaxLevel);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            deathState = reader.ReadSByte();
            deathCount = reader.ReadVarUShort();
            deathMaxLevel = reader.ReadVarUShort();
        }
    }
}