

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class CharacterBaseInformations : CharacterMinimalPlusLookInformations
    {
        public const short Id = 4381;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public bool sex;
        public short prestige;
        
        public CharacterBaseInformations()
        {
        }
        
        public CharacterBaseInformations(ulong id, string name, ushort level, Types.EntityLook entityLook, sbyte breed, bool sex, short prestige)
         : base(id, name, level, entityLook, breed)
        {
            this.sex = sex;
            this.prestige = prestige;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteBoolean(sex);
            writer.WriteVarShort(prestige);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            sex = reader.ReadBoolean();
            prestige = reader.ReadVarShort();
        }
    }
}