

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceSummaryRequestMessage : PaginationRequestAbstractMessage
    {
        public const uint Id = 3299;
        public override uint MessageId => Id;
        
        public bool hideFullFilter;
        public bool followingAllianceCriteria;
        public bool sortDescending;
        public int filterType;
        public string textFilter;
        public IEnumerable<uint> criterionFilter;
        public sbyte sortType;
        public IEnumerable<uint> languagesFilter;
        public IEnumerable<sbyte> recruitmentTypeFilter;
        public short minPlayerLevelFilter;
        public short maxPlayerLevelFilter;
        
        public AllianceSummaryRequestMessage()
        { }
        
        public AllianceSummaryRequestMessage(double offset, uint count, bool hideFullFilter, bool followingAllianceCriteria, bool sortDescending, int filterType, string textFilter, IEnumerable<uint> criterionFilter, sbyte sortType, IEnumerable<uint> languagesFilter, IEnumerable<sbyte> recruitmentTypeFilter, short minPlayerLevelFilter, short maxPlayerLevelFilter)
         : base(offset, count)
        {
            this.hideFullFilter = hideFullFilter;
            this.followingAllianceCriteria = followingAllianceCriteria;
            this.sortDescending = sortDescending;
            this.filterType = filterType;
            this.textFilter = textFilter;
            this.criterionFilter = criterionFilter;
            this.sortType = sortType;
            this.languagesFilter = languagesFilter;
            this.recruitmentTypeFilter = recruitmentTypeFilter;
            this.minPlayerLevelFilter = minPlayerLevelFilter;
            this.maxPlayerLevelFilter = maxPlayerLevelFilter;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, hideFullFilter);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, followingAllianceCriteria);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 2, sortDescending);
            writer.WriteByte(flag1);
            writer.WriteInt(filterType);
            writer.WriteUTF(textFilter);
            writer.WriteShort((short)criterionFilter.Count());
            foreach (var objectToSend in criterionFilter)
            {
                 writer.WriteVarUInt(objectToSend);
            }
            writer.WriteSByte(sortType);
            writer.WriteShort((short)languagesFilter.Count());
            foreach (var objectToSend in languagesFilter)
            {
                 writer.WriteVarUInt(objectToSend);
            }
            writer.WriteShort((short)recruitmentTypeFilter.Count());
            foreach (var objectToSend in recruitmentTypeFilter)
            {
                 writer.WriteSByte(objectToSend);
            }
            writer.WriteShort(minPlayerLevelFilter);
            writer.WriteShort(maxPlayerLevelFilter);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            byte flag1 = reader.ReadByte();
            hideFullFilter = BooleanByteWrapper.GetFlag(flag1, 0);
            followingAllianceCriteria = BooleanByteWrapper.GetFlag(flag1, 1);
            sortDescending = BooleanByteWrapper.GetFlag(flag1, 2);
            filterType = reader.ReadInt();
            textFilter = reader.ReadUTF();
            var criterionFilterCount = reader.ReadUShort();
            var criterionFilter_ = new uint[criterionFilterCount];
            for (var criterionFilterIndex = 0; criterionFilterIndex < criterionFilterCount; criterionFilterIndex++)
            {
                 criterionFilter_[criterionFilterIndex] = reader.ReadVarUInt();
            }
            criterionFilter = criterionFilter_;
            sortType = reader.ReadSByte();
            var languagesFilterCount = reader.ReadUShort();
            var languagesFilter_ = new uint[languagesFilterCount];
            for (var languagesFilterIndex = 0; languagesFilterIndex < languagesFilterCount; languagesFilterIndex++)
            {
                 languagesFilter_[languagesFilterIndex] = reader.ReadVarUInt();
            }
            languagesFilter = languagesFilter_;
            var recruitmentTypeFilterCount = reader.ReadUShort();
            var recruitmentTypeFilter_ = new sbyte[recruitmentTypeFilterCount];
            for (var recruitmentTypeFilterIndex = 0; recruitmentTypeFilterIndex < recruitmentTypeFilterCount; recruitmentTypeFilterIndex++)
            {
                 recruitmentTypeFilter_[recruitmentTypeFilterIndex] = reader.ReadSByte();
            }
            recruitmentTypeFilter = recruitmentTypeFilter_;
            minPlayerLevelFilter = reader.ReadShort();
            maxPlayerLevelFilter = reader.ReadShort();
        }
    }
}