

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceModificationResultMessage : Message
    {
        public const uint Id = 1267;
        public override uint MessageId => Id;
        
        public sbyte result;
        
        public AllianceModificationResultMessage()
        { }
        
        public AllianceModificationResultMessage(sbyte result)
        {
            this.result = result;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(result);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            result = reader.ReadSByte();
        }
    }
}