

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceRightsUpdateMessage : Message
    {
        public const uint Id = 1711;
        public override uint MessageId => Id;
        
        public uint rankId;
        public IEnumerable<uint> rights;
        
        public AllianceRightsUpdateMessage()
        { }
        
        public AllianceRightsUpdateMessage(uint rankId, IEnumerable<uint> rights)
        {
            this.rankId = rankId;
            this.rights = rights;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(rankId);
            writer.WriteShort((short)rights.Count());
            foreach (var objectToSend in rights)
            {
                 writer.WriteVarUInt(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            rankId = reader.ReadVarUInt();
            var rightsCount = reader.ReadUShort();
            var rights_ = new uint[rightsCount];
            for (var rightsIndex = 0; rightsIndex < rightsCount; rightsIndex++)
            {
                 rights_[rightsIndex] = reader.ReadVarUInt();
            }
            rights = rights_;
        }
    }
}