

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceMemberOnlineStatusMessage : Message
    {
        public const uint Id = 1867;
        public override uint MessageId => Id;
        
        public ulong memberId;
        public bool online;
        
        public AllianceMemberOnlineStatusMessage()
        { }
        
        public AllianceMemberOnlineStatusMessage(ulong memberId, bool online)
        {
            this.memberId = memberId;
            this.online = online;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(memberId);
            writer.WriteBoolean(online);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            memberId = reader.ReadVarULong();
            online = reader.ReadBoolean();
        }
    }
}