

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class AllianceMemberInformationUpdateMessage : Message
    {
        public const uint Id = 8221;
        public override uint MessageId => Id;
        
        public Types.AllianceMemberInfo member;
        
        public AllianceMemberInformationUpdateMessage()
        { }
        
        public AllianceMemberInformationUpdateMessage(Types.AllianceMemberInfo member)
        {
            this.member = member;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            member.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            member = new Types.AllianceMemberInfo();
            member.Deserialize(reader);
        }
    }
}