using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items.Usables
{
    public class ItemsFairyRelator
    {
        public static string FetchQuery = "SELECT * FROM items_fairy";
    }

    [TableName("items_fairy")]
    public class ItemsFairynRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("ItemId", false)]
        public int ItemId
        {
            get;
            set;
        }

        public int SpellId
        {
            get;
            set;
        }

        public int SpellLevel
        {
            get;
            set;
        }

        public int CallDelay
        {
            get;
            set;
        }

        public int DelaySeconds
        {
            get;
            set;
        }
    }
}