

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class JobBookSubscriptionMessage : Message
    {
        public const uint Id = 9108;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.JobBookSubscription> subscriptions;
        
        public JobBookSubscriptionMessage()
        { }
        
        public JobBookSubscriptionMessage(IEnumerable<Types.JobBookSubscription> subscriptions)
        {
            this.subscriptions = subscriptions;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)subscriptions.Count());
            foreach (var objectToSend in subscriptions)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var subscriptionsCount = reader.ReadUShort();
            var subscriptions_ = new Types.JobBookSubscription[subscriptionsCount];
            for (var subscriptionsIndex = 0; subscriptionsIndex < subscriptionsCount; subscriptionsIndex++)
            {
                 var objectToAdd = new Types.JobBookSubscription();
                 objectToAdd.Deserialize(reader);
                 subscriptions_[subscriptionsIndex] = objectToAdd;
            }
            subscriptions = subscriptions_;
        }
    }
}