

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class JobCrafterDirectoryRemoveMessage : Message
    {
        public const uint Id = 8864;
        public override uint MessageId => Id;
        
        public sbyte jobId;
        public ulong playerId;
        
        public JobCrafterDirectoryRemoveMessage()
        { }
        
        public JobCrafterDirectoryRemoveMessage(sbyte jobId, ulong playerId)
        {
            this.jobId = jobId;
            this.playerId = playerId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(jobId);
            writer.WriteVarULong(playerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            jobId = reader.ReadSByte();
            playerId = reader.ReadVarULong();
        }
    }
}