

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class JobDescriptionMessage : Message
    {
        public const uint Id = 430;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.JobDescription> jobsDescription;
        
        public JobDescriptionMessage()
        { }
        
        public JobDescriptionMessage(IEnumerable<Types.JobDescription> jobsDescription)
        {
            this.jobsDescription = jobsDescription;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)jobsDescription.Count());
            foreach (var objectToSend in jobsDescription)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var jobsDescriptionCount = reader.ReadUShort();
            var jobsDescription_ = new Types.JobDescription[jobsDescriptionCount];
            for (var jobsDescriptionIndex = 0; jobsDescriptionIndex < jobsDescriptionCount; jobsDescriptionIndex++)
            {
                 var objectToAdd = new Types.JobDescription();
                 objectToAdd.Deserialize(reader);
                 jobsDescription_[jobsDescriptionIndex] = objectToAdd;
            }
            jobsDescription = jobsDescription_;
        }
    }
}