using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Misc.Notify
{
    public class NotifyRelator
    {
        public static string FetchQuery = "SELECT * FROM player_notify";
    }

    [TableName("player_notify")]
    public class NotifyRecord : IAutoGeneratedRecord
    {
        public long Id { get; set; }

        public long AccountId { get; set; }

        public string NotifyMessage { get; set; }

        public Boolean Active { get; set; }

        public string ByAdmin { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime UpdateDate { get; set; }

        [Ignore]
        public bool IsNew { get; set; }

        [Ignore]
        public bool IsUpdated { get; set; }
    }
}