

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class ObjectGroundAddedMessage : Message
    {
        public const uint Id = 8098;
        public override uint MessageId => Id;
        
        public ushort cellId;
        public uint objectGID;
        
        public ObjectGroundAddedMessage()
        { }
        
        public ObjectGroundAddedMessage(ushort cellId, uint objectGID)
        {
            this.cellId = cellId;
            this.objectGID = objectGID;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(cellId);
            writer.WriteVarUInt(objectGID);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            cellId = reader.ReadVarUShort();
            objectGID = reader.ReadVarUInt();
        }
    }
}