

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AbstractCharacterInformation
    {
        public const short Id = 4664;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public ulong id;
        
        public AbstractCharacterInformation()
        {
        }
        
        public AbstractCharacterInformation(ulong id)
        {
            this.id = id;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(id);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            id = reader.ReadVarULong();
        }
    }
}