

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class StorageTabInformation
    {
        public const short Id = 3410;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public string name;
        public uint tabNumber;
        public uint picto;
        public uint openRight;
        public uint dropRight;
        public uint takeRight;
        public IEnumerable<uint> dropTypeLimitation;
        
        public StorageTabInformation()
        {
        }
        
        public StorageTabInformation(string name, uint tabNumber, uint picto, uint openRight, uint dropRight, uint takeRight, IEnumerable<uint> dropTypeLimitation)
        {
            this.name = name;
            this.tabNumber = tabNumber;
            this.picto = picto;
            this.openRight = openRight;
            this.dropRight = dropRight;
            this.takeRight = takeRight;
            this.dropTypeLimitation = dropTypeLimitation;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(name);
            writer.WriteVarUInt(tabNumber);
            writer.WriteVarUInt(picto);
            writer.WriteVarUInt(openRight);
            writer.WriteVarUInt(dropRight);
            writer.WriteVarUInt(takeRight);
            writer.WriteShort((short)dropTypeLimitation.Count());
            foreach (var objectToSend in dropTypeLimitation)
            {
                 writer.WriteVarUInt(objectToSend);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            name = reader.ReadUTF();
            tabNumber = reader.ReadVarUInt();
            picto = reader.ReadVarUInt();
            openRight = reader.ReadVarUInt();
            dropRight = reader.ReadVarUInt();
            takeRight = reader.ReadVarUInt();
            var dropTypeLimitationCount = reader.ReadUShort();
            var dropTypeLimitation_ = new uint[dropTypeLimitationCount];
            for (var dropTypeLimitationIndex = 0; dropTypeLimitationIndex < dropTypeLimitationCount; dropTypeLimitationIndex++)
            {
                 dropTypeLimitation_[dropTypeLimitationIndex] = reader.ReadVarUInt();
            }
            dropTypeLimitation = dropTypeLimitation_;
        }
    }
}