

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class UpdatedStorageTabInformation
    {
        public const short Id = 265;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public string name;
        public uint tabNumber;
        public uint picto;
        public IEnumerable<uint> dropTypeLimitation;
        
        public UpdatedStorageTabInformation()
        {
        }
        
        public UpdatedStorageTabInformation(string name, uint tabNumber, uint picto, IEnumerable<uint> dropTypeLimitation)
        {
            this.name = name;
            this.tabNumber = tabNumber;
            this.picto = picto;
            this.dropTypeLimitation = dropTypeLimitation;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(name);
            writer.WriteVarUInt(tabNumber);
            writer.WriteVarUInt(picto);
            writer.WriteShort((short)dropTypeLimitation.Count());
            foreach (var objectToSend in dropTypeLimitation)
            {
                 writer.WriteVarUInt(objectToSend);
            }
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            name = reader.ReadUTF();
            tabNumber = reader.ReadVarUInt();
            picto = reader.ReadVarUInt();
            var dropTypeLimitationCount = reader.ReadUShort();
            var dropTypeLimitation_ = new uint[dropTypeLimitationCount];
            for (var dropTypeLimitationIndex = 0; dropTypeLimitationIndex < dropTypeLimitationCount; dropTypeLimitationIndex++)
            {
                 dropTypeLimitation_[dropTypeLimitationIndex] = reader.ReadVarUInt();
            }
            dropTypeLimitation = dropTypeLimitation_;
        }
    }
}