

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameDataPlayFarmObjectAnimationMessage : Message
    {
        public const uint Id = 5773;
        public override uint MessageId => Id;
        
        public IEnumerable<ushort> cellId;
        
        public GameDataPlayFarmObjectAnimationMessage()
        { }
        
        public GameDataPlayFarmObjectAnimationMessage(IEnumerable<ushort> cellId)
        {
            this.cellId = cellId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)cellId.Count());
            foreach (var objectToSend in cellId)
            {
                 writer.WriteVarUShort(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var cellIdCount = reader.ReadUShort();
            var cellId_ = new ushort[cellIdCount];
            for (var cellIdIndex = 0; cellIdIndex < cellIdCount; cellIdIndex++)
            {
                 cellId_[cellIdIndex] = reader.ReadVarUShort();
            }
            cellId = cellId_;
        }
    }
}