

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class HouseInformationsForGuild : HouseInformations
    {
        public const short Id = 7095;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public int instanceId;
        public bool secondHand;
        public Types.AccountTagInformation ownerTag;
        public short worldX;
        public short worldY;
        public double mapId;
        public ushort subAreaId;
        public IEnumerable<int> skillListIds;
        public uint guildshareParams;
        
        public HouseInformationsForGuild()
        {
        }
        
        public HouseInformationsForGuild(uint houseId, ushort modelId, int instanceId, bool secondHand, Types.AccountTagInformation ownerTag, short worldX, short worldY, double mapId, ushort subAreaId, IEnumerable<int> skillListIds, uint guildshareParams)
         : base(houseId, modelId)
        {
            this.instanceId = instanceId;
            this.secondHand = secondHand;
            this.ownerTag = ownerTag;
            this.worldX = worldX;
            this.worldY = worldY;
            this.mapId = mapId;
            this.subAreaId = subAreaId;
            this.skillListIds = skillListIds;
            this.guildshareParams = guildshareParams;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(instanceId);
            writer.WriteBoolean(secondHand);
            ownerTag.Serialize(writer);
            writer.WriteShort(worldX);
            writer.WriteShort(worldY);
            writer.WriteDouble(mapId);
            writer.WriteVarUShort(subAreaId);
            writer.WriteShort((short)skillListIds.Count());
            foreach (var objectToSend in skillListIds)
            {
                 writer.WriteInt(objectToSend);
            }
            writer.WriteVarUInt(guildshareParams);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            instanceId = reader.ReadInt();
            secondHand = reader.ReadBoolean();
            ownerTag = new Types.AccountTagInformation();
            ownerTag.Deserialize(reader);
            worldX = reader.ReadShort();
            worldY = reader.ReadShort();
            mapId = reader.ReadDouble();
            subAreaId = reader.ReadVarUShort();
            var skillListIdsCount = reader.ReadUShort();
            var skillListIds_ = new int[skillListIdsCount];
            for (var skillListIdsIndex = 0; skillListIdsIndex < skillListIdsCount; skillListIdsIndex++)
            {
                 skillListIds_[skillListIdsIndex] = reader.ReadInt();
            }
            skillListIds = skillListIds_;
            guildshareParams = reader.ReadVarUInt();
        }
    }
}