

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class HouseInformations
    {
        public const short Id = 1987;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public uint houseId;
        public ushort modelId;
        
        public HouseInformations()
        {
        }
        
        public HouseInformations(uint houseId, ushort modelId)
        {
            this.houseId = houseId;
            this.modelId = modelId;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(houseId);
            writer.WriteVarUShort(modelId);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            houseId = reader.ReadVarUInt();
            modelId = reader.ReadVarUShort();
        }
    }
}