using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class DungeonsRelator
    {
        public static string FetchQuery = "SELECT * FROM world_dungeons";
    }

    [TableName("world_dungeons")]
    public class DungeonsRecord : IAutoGeneratedRecord
    {
        private uint[] m_Maps;
        private string m_MapsCSV;

        public int Id { get; set; }

        public string Name { get; set; }

        public int NameId { get; set; }

        public int OptimalPlayerLevel { get; set; }

        [Ignore]
        public uint[] Maps
        {
            get
            {
                return m_Maps;
            }
            set
            {
                m_Maps = value;
                m_MapsCSV = value.ToCSV(",");
            }
        }

        public string MapsCSV
        {
            get
            {
                return m_MapsCSV;
            }
            set
            {
                if (!string.IsNullOrEmpty(value))
                {
                    m_MapsCSV = value;
                    m_Maps = value.FromCSV<uint>(",");
                }
            }
        }
    }
}