using System.Collections.Generic;
using System.Linq;
using ServiceStack.Text;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.Server.WorldServer.Game.Spells;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Monsters;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class MonsterGradeRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_grades";
    }

    [TableName("monsters_grades")]
    [D2OClass("MonsterGrade", "com.ankamagames.dofus.datacenter.monsters")]
    public class MonsterGrade : IAssignedByD2O, ISaveIntercepter, IAutoGeneratedRecord
    {
        private List<MonsterSpell> m_spellsTemplates;
        private string m_statsJSON;
        private MonsterTemplate m_template;
        private int m_wisdom;
        private List<Spell> m_spells;

        public MonsterGrade()
        {
            Stats = new Dictionary<PlayerFields, short>();
        }

        [PrimaryKey("Id", true)]
        public int Id { get; set; }

        [DefaultSetting(0)]
        public uint GradeId { get; set; }

        [DefaultSetting(0)]
        public int MonsterId { get; set; }

        [DefaultSetting(0)]
        public uint Level { get; set; }

        [DefaultSetting(0)]
        public short Vitality { get; set; }

        [DefaultSetting(0)]
        public int PaDodge { get; set; }

        [DefaultSetting(0)]
        public int PmDodge { get; set; }

        [DefaultSetting(0)]
        public short Wisdom
        {
            get { return (short)m_wisdom; }
            set { m_wisdom = value; }
        }

        [DefaultSetting(0)]
        public int EarthResistance { get; set; }

        [DefaultSetting(0)]
        public int AirResistance { get; set; }

        [DefaultSetting(0)]
        public int FireResistance { get; set; }

        [DefaultSetting(0)]
        public int WaterResistance { get; set; }

        [DefaultSetting(0)]
        public int NeutralResistance { get; set; }

        [DefaultSetting(0)]
        public int GradeXp { get; set; }

        [DefaultSetting(0)]
        public int LifePoints { get; set; }

        [DefaultSetting(0)]
        public int ActionPoints { get; set; }

        [DefaultSetting(0)]
        public int MovementPoints { get; set; }

        [DefaultSetting(0)]
        public int DamageReflect { get; set; }

        [DefaultSetting(0)]
        public uint HiddenLevel { get; set; }

        [DefaultSetting(0)]
        public int Strength { get; set; }

        [DefaultSetting(0)]
        public int Intelligence { get; set; }

        [DefaultSetting(0)]
        public int Chance { get; set; }

        [DefaultSetting(0)]
        public int Agility { get; set; }

        [DefaultSetting(0)]
        public int BonusRange { get; set; }

        [DefaultSetting(0)]
        public int StartingSpellId { get; set; }

        [DefaultSetting(0)]
        public short TackleEvade { get; set; }

        [DefaultSetting(0)]
        public short TackleBlock { get; set; }

        [Ignore]
        public MonsterTemplate Template
        {
            get { return m_template ?? (m_template = MonsterManager.Instance.GetTemplate(MonsterId)); }
            set
            {
                m_template = value;
                MonsterId = value.Id;
            }
        }

        [Ignore]
        public Dictionary<PlayerFields, short> Stats { get; set; }

        [Ignore]
        public List<MonsterSpell> SpellsTemplates
        {
            get { return m_spellsTemplates ?? (m_spellsTemplates = MonsterManager.Instance.GetMonsterGradeSpells(Id)); }
        }

        [Ignore]
        public List<Spell> Spells
        {
            get
            {
                //return Template.SpellsCSV.FromCSV<uint>(",").Where(x => SpellManager.Instance.GetSpellTemplate(x) != null).Select(x => new Spell((int)x, (byte)this.GradeId)).ToList();
                return m_spells ?? (m_spells = SpellsTemplates.Select(entry => new Spell(entry)).ToList());
            }
        }

        public void ReloadSpells()
        {
            m_spells = null;
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var grade = (DofusProtocol.D2oClasses.MonsterGrade)d2oObject;

            GradeId = grade.grade;
            MonsterId = grade.monsterId;
            Level = grade.level;
            Vitality = (short)grade.vitality;
            PaDodge = grade.paDodge;
            PmDodge = grade.pmDodge;
            Wisdom = (short)grade.wisdom;
            EarthResistance = grade.earthResistance;
            AirResistance = grade.airResistance;
            FireResistance = grade.fireResistance;
            WaterResistance = grade.waterResistance;
            NeutralResistance = grade.neutralResistance;
            GradeXp = grade.gradeXp;
            LifePoints = grade.lifePoints;
            ActionPoints = grade.actionPoints;
            MovementPoints = grade.movementPoints;
            DamageReflect = grade.damageReflect;
            HiddenLevel = grade.hiddenLevel;
            Strength = grade.strength;
            Intelligence = grade.intelligence;
            Chance = grade.chance;
            Agility = grade.agility;
            BonusRange = grade.bonusRange;
            StartingSpellId = grade.startingSpellId;
        }

        #endregion

        #region ISaveIntercepter Members

        public void BeforeSave(bool insert)
        {
            m_statsJSON = Stats.ToJson();
        }

        #endregion
    }
}