

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TaxCollectorPresetSpellUpdatedMessage : Message
    {
        public const uint Id = 4921;
        public override uint MessageId => Id;
        
        public Types.Uuid presetId;
        public IEnumerable<Types.TaxCollectorOrderedSpell> taxCollectorSpells;
        
        public TaxCollectorPresetSpellUpdatedMessage()
        { }
        
        public TaxCollectorPresetSpellUpdatedMessage(Types.Uuid presetId, IEnumerable<Types.TaxCollectorOrderedSpell> taxCollectorSpells)
        {
            this.presetId = presetId;
            this.taxCollectorSpells = taxCollectorSpells;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            presetId.Serialize(writer);
            writer.WriteShort((short)taxCollectorSpells.Count());
            foreach (var objectToSend in taxCollectorSpells)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            presetId = new Types.Uuid();
            presetId.Deserialize(reader);
            var taxCollectorSpellsCount = reader.ReadUShort();
            var taxCollectorSpells_ = new Types.TaxCollectorOrderedSpell[taxCollectorSpellsCount];
            for (var taxCollectorSpellsIndex = 0; taxCollectorSpellsIndex < taxCollectorSpellsCount; taxCollectorSpellsIndex++)
            {
                 var objectToAdd = new Types.TaxCollectorOrderedSpell();
                 objectToAdd.Deserialize(reader);
                 taxCollectorSpells_[taxCollectorSpellsIndex] = objectToAdd;
            }
            taxCollectorSpells = taxCollectorSpells_;
        }
    }
}