

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TaxCollectorMovementsOfflineMessage : Message
    {
        public const uint Id = 8947;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.TaxCollectorMovement> movements;
        
        public TaxCollectorMovementsOfflineMessage()
        { }
        
        public TaxCollectorMovementsOfflineMessage(IEnumerable<Types.TaxCollectorMovement> movements)
        {
            this.movements = movements;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)movements.Count());
            foreach (var objectToSend in movements)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var movementsCount = reader.ReadUShort();
            var movements_ = new Types.TaxCollectorMovement[movementsCount];
            for (var movementsIndex = 0; movementsIndex < movementsCount; movementsIndex++)
            {
                 var objectToAdd = new Types.TaxCollectorMovement();
                 objectToAdd.Deserialize(reader);
                 movements_[movementsIndex] = objectToAdd;
            }
            movements = movements_;
        }
    }
}