

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TaxCollectorPresetsMessage : Message
    {
        public const uint Id = 3825;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.TaxCollectorPreset> presets;
        
        public TaxCollectorPresetsMessage()
        { }
        
        public TaxCollectorPresetsMessage(IEnumerable<Types.TaxCollectorPreset> presets)
        {
            this.presets = presets;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)presets.Count());
            foreach (var objectToSend in presets)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var presetsCount = reader.ReadUShort();
            var presets_ = new Types.TaxCollectorPreset[presetsCount];
            for (var presetsIndex = 0; presetsIndex < presetsCount; presetsIndex++)
            {
                 var objectToAdd = new Types.TaxCollectorPreset();
                 objectToAdd.Deserialize(reader);
                 presets_[presetsIndex] = objectToAdd;
            }
            presets = presets_;
        }
    }
}