

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TaxCollectorStateUpdateMessage : Message
    {
        public const uint Id = 6454;
        public override uint MessageId => Id;
        
        public double uniqueId;
        public sbyte state;
        
        public TaxCollectorStateUpdateMessage()
        { }
        
        public TaxCollectorStateUpdateMessage(double uniqueId, sbyte state)
        {
            this.uniqueId = uniqueId;
            this.state = state;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(uniqueId);
            writer.WriteSByte(state);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            uniqueId = reader.ReadDouble();
            state = reader.ReadSByte();
        }
    }
}