

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PartyKickRequestMessage : AbstractPartyMessage
    {
        public const uint Id = 8208;
        public override uint MessageId => Id;
        
        public ulong playerId;
        
        public PartyKickRequestMessage()
        { }
        
        public PartyKickRequestMessage(uint partyId, ulong playerId)
         : base(partyId)
        {
            this.playerId = playerId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(playerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            playerId = reader.ReadVarULong();
        }
    }
}