

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PartyInvitationDungeonDetailsMessage : PartyInvitationDetailsMessage
    {
        public const uint Id = 2147;
        public override uint MessageId => Id;
        
        public ushort dungeonId;
        public IEnumerable<bool> playersDungeonReady;
        
        public PartyInvitationDungeonDetailsMessage()
        { }
        
        public PartyInvitationDungeonDetailsMessage(uint partyId, sbyte partyType, string partyName, ulong fromId, string fromName, ulong leaderId, IEnumerable<Types.PartyInvitationMemberInformations> members, IEnumerable<Types.PartyGuestInformations> guests, ushort dungeonId, IEnumerable<bool> playersDungeonReady)
         : base(partyId, partyType, partyName, fromId, fromName, leaderId, members, guests)
        {
            this.dungeonId = dungeonId;
            this.playersDungeonReady = playersDungeonReady;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUShort(dungeonId);
            writer.WriteShort((short)playersDungeonReady.Count());
            foreach (var objectToSend in playersDungeonReady)
            {
                 writer.WriteBoolean(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            dungeonId = reader.ReadVarUShort();
            var playersDungeonReadyCount = reader.ReadUShort();
            var playersDungeonReady_ = new bool[playersDungeonReadyCount];
            for (var playersDungeonReadyIndex = 0; playersDungeonReadyIndex < playersDungeonReadyCount; playersDungeonReadyIndex++)
            {
                 playersDungeonReady_[playersDungeonReadyIndex] = reader.ReadBoolean();
            }
            playersDungeonReady = playersDungeonReady_;
        }
    }
}