

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PartyCancelInvitationNotificationMessage : AbstractPartyEventMessage
    {
        public const uint Id = 3506;
        public override uint MessageId => Id;
        
        public ulong cancelerId;
        public ulong guestId;
        
        public PartyCancelInvitationNotificationMessage()
        { }
        
        public PartyCancelInvitationNotificationMessage(uint partyId, ulong cancelerId, ulong guestId)
         : base(partyId)
        {
            this.cancelerId = cancelerId;
            this.guestId = guestId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarULong(cancelerId);
            writer.WriteVarULong(guestId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            cancelerId = reader.ReadVarULong();
            guestId = reader.ReadVarULong();
        }
    }
}