

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PartyLocateMembersMessage : AbstractPartyMessage
    {
        public const uint Id = 594;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.PartyMemberGeoPosition> geopositions;
        
        public PartyLocateMembersMessage()
        { }
        
        public PartyLocateMembersMessage(uint partyId, IEnumerable<Types.PartyMemberGeoPosition> geopositions)
         : base(partyId)
        {
            this.geopositions = geopositions;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)geopositions.Count());
            foreach (var objectToSend in geopositions)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var geopositionsCount = reader.ReadUShort();
            var geopositions_ = new Types.PartyMemberGeoPosition[geopositionsCount];
            for (var geopositionsIndex = 0; geopositionsIndex < geopositionsCount; geopositionsIndex++)
            {
                 var objectToAdd = new Types.PartyMemberGeoPosition();
                 objectToAdd.Deserialize(reader);
                 geopositions_[geopositionsIndex] = objectToAdd;
            }
            geopositions = geopositions_;
        }
    }
}