

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("BreachDungeonModificator", "com.ankamagames.dofus.datacenter.breach")]
    [Serializable]
    public class BreachDungeonModificator : IDataObject, IIndexedData
    {
        public const String MODULE = "BreachDungeonModificators";
        public uint id;
        public uint modificatorId;
        public String criterion;
        public double additionalRewardPercent;
        public double score;
        public Boolean isPositiveForPlayers;
        public String tooltipBaseline;
        int IIndexedData.Id
        {
            get { return (int)id; }
        }
        [D2OIgnore]
        public uint Id
        {
            get { return this.id; }
            set { this.id = value; }
        }
        [D2OIgnore]
        public uint ModificatorId
        {
            get { return this.modificatorId; }
            set { this.modificatorId = value; }
        }
        [D2OIgnore]
        public String Criterion
        {
            get { return this.criterion; }
            set { this.criterion = value; }
        }
        [D2OIgnore]
        public double AdditionalRewardPercent
        {
            get { return this.additionalRewardPercent; }
            set { this.additionalRewardPercent = value; }
        }
        [D2OIgnore]
        public double Score
        {
            get { return this.score; }
            set { this.score = value; }
        }
        [D2OIgnore]
        public Boolean IsPositiveForPlayers
        {
            get { return this.isPositiveForPlayers; }
            set { this.isPositiveForPlayers = value; }
        }
        [D2OIgnore]
        public String TooltipBaseline
        {
            get { return this.tooltipBaseline; }
            set { this.tooltipBaseline = value; }
        }
    }
}