

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("SocialRightGroup", "com.ankamagames.dofus.datacenter.social")]
    [Serializable]
    public class SocialRightGroup : IDataObject, IIndexedData
    {
        public int id;
        [I18NField]
        public uint nameId;
        public int order;
        public List<SocialRight> rights;
        int IIndexedData.Id
        {
            get { return (int)id; }
        }
        [D2OIgnore]
        public int Id
        {
            get { return this.id; }
            set { this.id = value; }
        }
        [D2OIgnore]
        public uint NameId
        {
            get { return this.nameId; }
            set { this.nameId = value; }
        }
        [D2OIgnore]
        public int Order
        {
            get { return this.order; }
            set { this.order = value; }
        }
        [D2OIgnore]
        public List<SocialRight> Rights
        {
            get { return this.rights; }
            set { this.rights = value; }
        }
    }
}