

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameActionItemListMessage : Message
    {
        public const uint Id = 4354;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.GameActionItem> actions;
        
        public GameActionItemListMessage()
        { }
        
        public GameActionItemListMessage(IEnumerable<Types.GameActionItem> actions)
        {
            this.actions = actions;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)actions.Count());
            foreach (var objectToSend in actions)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var actionsCount = reader.ReadUShort();
            var actions_ = new Types.GameActionItem[actionsCount];
            for (var actionsIndex = 0; actionsIndex < actionsCount; actionsIndex++)
            {
                 var objectToAdd = new Types.GameActionItem();
                 objectToAdd.Deserialize(reader);
                 actions_[actionsIndex] = objectToAdd;
            }
            actions = actions_;
        }
    }
}