

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class TeleportDestination
    {
        public const short Id = 4498;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public sbyte type;
        public double mapId;
        public ushort subAreaId;
        public ushort level;
        public ushort cost;
        
        public TeleportDestination()
        {
        }
        
        public TeleportDestination(sbyte type, double mapId, ushort subAreaId, ushort level, ushort cost)
        {
            this.type = type;
            this.mapId = mapId;
            this.subAreaId = subAreaId;
            this.level = level;
            this.cost = cost;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(type);
            writer.WriteDouble(mapId);
            writer.WriteVarUShort(subAreaId);
            writer.WriteVarUShort(level);
            writer.WriteVarUShort(cost);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            type = reader.ReadSByte();
            mapId = reader.ReadDouble();
            subAreaId = reader.ReadVarUShort();
            level = reader.ReadVarUShort();
            cost = reader.ReadVarUShort();
        }
    }
}