

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class BreachBranchesMessage : Message
    {
        public const uint Id = 4087;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.ExtendedBreachBranch> branches;
        
        public BreachBranchesMessage()
        { }
        
        public BreachBranchesMessage(IEnumerable<Types.ExtendedBreachBranch> branches)
        {
            this.branches = branches;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)branches.Count());
            foreach (var objectToSend in branches)
            {
                 writer.WriteShort(objectToSend.TypeId);
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var branchesCount = reader.ReadUShort();
            var branches_ = new Types.ExtendedBreachBranch[branchesCount];
            for (var branchesIndex = 0; branchesIndex < branchesCount; branchesIndex++)
            {
                 var objectToAdd = Types.ProtocolTypeManager.GetInstance<Types.ExtendedBreachBranch>(reader.ReadShort());
                 objectToAdd.Deserialize(reader);
                 branches_[branchesIndex] = objectToAdd;
            }
            branches = branches_;
        }
    }
}