

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class UpdateMapPlayersAgressableStatusMessage : Message
    {
        public const uint Id = 2209;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.AgressableStatusMessage> playerAvAMessages;
        
        public UpdateMapPlayersAgressableStatusMessage()
        { }
        
        public UpdateMapPlayersAgressableStatusMessage(IEnumerable<Types.AgressableStatusMessage> playerAvAMessages)
        {
            this.playerAvAMessages = playerAvAMessages;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)playerAvAMessages.Count());
            foreach (var objectToSend in playerAvAMessages)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var playerAvAMessagesCount = reader.ReadUShort();
            var playerAvAMessages_ = new Types.AgressableStatusMessage[playerAvAMessagesCount];
            for (var playerAvAMessagesIndex = 0; playerAvAMessagesIndex < playerAvAMessagesCount; playerAvAMessagesIndex++)
            {
                 var objectToAdd = new Types.AgressableStatusMessage();
                 objectToAdd.Deserialize(reader);
                 playerAvAMessages_[playerAvAMessagesIndex] = objectToAdd;
            }
            playerAvAMessages = playerAvAMessages_;
        }
    }
}