

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class FollowedQuestsMessage : Message
    {
        public const uint Id = 7010;
        public override uint MessageId => Id;
        
        public IEnumerable<Types.QuestActiveDetailedInformations> quests;
        
        public FollowedQuestsMessage()
        { }
        
        public FollowedQuestsMessage(IEnumerable<Types.QuestActiveDetailedInformations> quests)
        {
            this.quests = quests;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)quests.Count());
            foreach (var objectToSend in quests)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var questsCount = reader.ReadUShort();
            var quests_ = new Types.QuestActiveDetailedInformations[questsCount];
            for (var questsIndex = 0; questsIndex < questsCount; questsIndex++)
            {
                 var objectToAdd = new Types.QuestActiveDetailedInformations();
                 objectToAdd.Deserialize(reader);
                 quests_[questsIndex] = objectToAdd;
            }
            quests = quests_;
        }
    }
}