

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class FollowQuestObjectiveRequestMessage : Message
    {
        public const uint Id = 4169;
        public override uint MessageId => Id;
        
        public ushort questId;
        public short objectiveId;
        
        public FollowQuestObjectiveRequestMessage()
        { }
        
        public FollowQuestObjectiveRequestMessage(ushort questId, short objectiveId)
        {
            this.questId = questId;
            this.objectiveId = objectiveId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(questId);
            writer.WriteShort(objectiveId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            questId = reader.ReadVarUShort();
            objectiveId = reader.ReadShort();
        }
    }
}