

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class CharacterDeletionPrepareMessage : Message
    {
        public const uint Id = 4201;
        public override uint MessageId => Id;
        
        public ulong characterId;
        public string characterName;
        public string secretQuestion;
        public bool needSecretAnswer;
        
        public CharacterDeletionPrepareMessage()
        { }
        
        public CharacterDeletionPrepareMessage(ulong characterId, string characterName, string secretQuestion, bool needSecretAnswer)
        {
            this.characterId = characterId;
            this.characterName = characterName;
            this.secretQuestion = secretQuestion;
            this.needSecretAnswer = needSecretAnswer;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarULong(characterId);
            writer.WriteUTF(characterName);
            writer.WriteUTF(secretQuestion);
            writer.WriteBoolean(needSecretAnswer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            characterId = reader.ReadVarULong();
            characterName = reader.ReadUTF();
            secretQuestion = reader.ReadUTF();
            needSecretAnswer = reader.ReadBoolean();
        }
    }
}