

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TaxCollectorEquipmentUpdateMessage : Message
    {
        public const uint Id = 6675;
        public override uint MessageId => Id;
        
        public double uniqueId;
        public Types.ObjectItem @object;
        public bool added;
        public Types.CharacterCharacteristics characteristics;
        
        public TaxCollectorEquipmentUpdateMessage()
        { }
        
        public TaxCollectorEquipmentUpdateMessage(double uniqueId, Types.ObjectItem @object, bool added, Types.CharacterCharacteristics characteristics)
        {
            this.uniqueId = uniqueId;
            this.@object = @object;
            this.added = added;
            this.characteristics = characteristics;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(uniqueId);
            @object.Serialize(writer);
            writer.WriteBoolean(added);
            characteristics.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            uniqueId = reader.ReadDouble();
            @object = new Types.ObjectItem();
            @object.Deserialize(reader);
            added = reader.ReadBoolean();
            characteristics = new Types.CharacterCharacteristics();
            characteristics.Deserialize(reader);
        }
    }
}