

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class PaginationAnswerAbstractMessage : Message
    {
        public const uint Id = 8699;
        public override uint MessageId => Id;
        
        public double offset;
        public uint count;
        public uint total;
        
        public PaginationAnswerAbstractMessage()
        { }
        
        public PaginationAnswerAbstractMessage(double offset, uint count, uint total)
        {
            this.offset = offset;
            this.count = count;
            this.total = total;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteDouble(offset);
            writer.WriteUInt(count);
            writer.WriteUInt(total);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            offset = reader.ReadDouble();
            count = reader.ReadUInt();
            total = reader.ReadUInt();
        }
    }
}