using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Lottery
{
    public class LotteryRewardsTableRelator
    {
        public static string FetchQuery = "SELECT * FROM lottery_rewards";
    }

    [TableName("lottery_rewards")]
    class LotteryRewards : IAutoGeneratedRecord
    {
        [PrimaryKey("ItemID")]
        public int ItemID
        {
            get;
            set;
        }

        public int Stack
        {
            get;
            set;
        }

        public int Probability
        {
            get;
            set;
        }

        public string Comment
        {
            get;
            set;
        }

    }
}
