

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class TitleSelectedMessage : Message
    {
        public const uint Id = 4882;
        public override uint MessageId => Id;
        
        public ushort titleId;
        
        public TitleSelectedMessage()
        { }
        
        public TitleSelectedMessage(ushort titleId)
        {
            this.titleId = titleId;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(titleId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            titleId = reader.ReadVarUShort();
        }
    }
}