

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class SurrenderStateMessage : Message
    {
        public const uint Id = 6810;
        public override uint MessageId => Id;
        
        public bool canSurrender;
        public bool permitVote;
        
        public SurrenderStateMessage()
        { }
        
        public SurrenderStateMessage(bool canSurrender, bool permitVote)
        {
            this.canSurrender = canSurrender;
            this.permitVote = permitVote;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            byte flag1 = 0;
            flag1 = BooleanByteWrapper.SetFlag(flag1, 0, canSurrender);
            flag1 = BooleanByteWrapper.SetFlag(flag1, 1, permitVote);
            writer.WriteByte(flag1);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            byte flag1 = reader.ReadByte();
            canSurrender = BooleanByteWrapper.GetFlag(flag1, 0);
            permitVote = BooleanByteWrapper.GetFlag(flag1, 1);
        }
    }
}