

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameFightUpdateTeamMessage : Message
    {
        public const uint Id = 5591;
        public override uint MessageId => Id;
        
        public ushort fightId;
        public Types.FightTeamInformations team;
        
        public GameFightUpdateTeamMessage()
        { }
        
        public GameFightUpdateTeamMessage(ushort fightId, Types.FightTeamInformations team)
        {
            this.fightId = fightId;
            this.team = team;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUShort(fightId);
            team.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightId = reader.ReadVarUShort();
            team = new Types.FightTeamInformations();
            team.Deserialize(reader);
        }
    }
}