

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameFightOptionToggleMessage : Message
    {
        public const uint Id = 4150;
        public override uint MessageId => Id;
        
        public sbyte option;
        
        public GameFightOptionToggleMessage()
        { }
        
        public GameFightOptionToggleMessage(sbyte option)
        {
            this.option = option;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(option);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            option = reader.ReadSByte();
        }
    }
}