

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class GameFightStartingMessage : Message
    {
        public const uint Id = 3380;
        public override uint MessageId => Id;
        
        public sbyte fightType;
        public ushort fightId;
        public double attackerId;
        public double defenderId;
        public bool containsBoss;
        public IEnumerable<int> monsters;
        
        public GameFightStartingMessage()
        { }
        
        public GameFightStartingMessage(sbyte fightType, ushort fightId, double attackerId, double defenderId, bool containsBoss, IEnumerable<int> monsters)
        {
            this.fightType = fightType;
            this.fightId = fightId;
            this.attackerId = attackerId;
            this.defenderId = defenderId;
            this.containsBoss = containsBoss;
            this.monsters = monsters;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(fightType);
            writer.WriteVarUShort(fightId);
            writer.WriteDouble(attackerId);
            writer.WriteDouble(defenderId);
            writer.WriteBoolean(containsBoss);
            writer.WriteShort((short)monsters.Count());
            foreach (var objectToSend in monsters)
            {
                 writer.WriteInt(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            fightType = reader.ReadSByte();
            fightId = reader.ReadVarUShort();
            attackerId = reader.ReadDouble();
            defenderId = reader.ReadDouble();
            containsBoss = reader.ReadBoolean();
            var monstersCount = reader.ReadUShort();
            var monsters_ = new int[monstersCount];
            for (var monstersIndex = 0; monstersIndex < monstersCount; monstersIndex++)
            {
                 monsters_[monstersIndex] = reader.ReadInt();
            }
            monsters = monsters_;
        }
    }
}