

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class BreachInvitationRequestMessage : Message
    {
        public const uint Id = 3577;
        public override uint MessageId => Id;
        
        public IEnumerable<ulong> guests;
        
        public BreachInvitationRequestMessage()
        { }
        
        public BreachInvitationRequestMessage(IEnumerable<ulong> guests)
        {
            this.guests = guests;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort((short)guests.Count());
            foreach (var objectToSend in guests)
            {
                 writer.WriteVarULong(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var guestsCount = reader.ReadUShort();
            var guests_ = new ulong[guestsCount];
            for (var guestsIndex = 0; guestsIndex < guestsCount; guestsIndex++)
            {
                 guests_[guestsIndex] = reader.ReadVarULong();
            }
            guests = guests_;
        }
    }
}