

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class AbstractFightDispellableEffect
    {
        public const short Id = 5248;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public uint uid;
        public double targetId;
        public short turnDuration;
        public sbyte dispelable;
        public ushort spellId;
        public uint effectId;
        public uint parentBoostUid;
        
        public AbstractFightDispellableEffect()
        {
        }
        
        public AbstractFightDispellableEffect(uint uid, double targetId, short turnDuration, sbyte dispelable, ushort spellId, uint effectId, uint parentBoostUid)
        {
            this.uid = uid;
            this.targetId = targetId;
            this.turnDuration = turnDuration;
            this.dispelable = dispelable;
            this.spellId = spellId;
            this.effectId = effectId;
            this.parentBoostUid = parentBoostUid;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteVarUInt(uid);
            writer.WriteDouble(targetId);
            writer.WriteShort(turnDuration);
            writer.WriteSByte(dispelable);
            writer.WriteVarUShort(spellId);
            writer.WriteVarUInt(effectId);
            writer.WriteVarUInt(parentBoostUid);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            uid = reader.ReadVarUInt();
            targetId = reader.ReadDouble();
            turnDuration = reader.ReadShort();
            dispelable = reader.ReadSByte();
            spellId = reader.ReadVarUShort();
            effectId = reader.ReadVarUInt();
            parentBoostUid = reader.ReadVarUInt();
        }
    }
}