

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class FightDetailedTemporaryBoostEffect : FightTemporaryBoostEffect
    {
        public const short Id = 1155;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public int arg1;
        public int arg2;
        public int arg3;
        
        public FightDetailedTemporaryBoostEffect()
        {
        }
        
        public FightDetailedTemporaryBoostEffect(uint uid, double targetId, short turnDuration, sbyte dispelable, ushort spellId, uint effectId, uint parentBoostUid, int delta, int arg1, int arg2, int arg3)
         : base(uid, targetId, turnDuration, dispelable, spellId, effectId, parentBoostUid, delta)
        {
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(arg1);
            writer.WriteInt(arg2);
            writer.WriteInt(arg3);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            arg1 = reader.ReadInt();
            arg2 = reader.ReadInt();
            arg3 = reader.ReadInt();
        }
    }
}