

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class ItemsPreset : Preset
    {
        public const short Id = 3328;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public IEnumerable<Types.ItemForPreset> items;
        public bool mountEquipped;
        public Types.EntityLook look;
        
        public ItemsPreset()
        {
        }
        
        public ItemsPreset(short id, IEnumerable<Types.ItemForPreset> items, bool mountEquipped, Types.EntityLook look)
         : base(id)
        {
            this.items = items;
            this.mountEquipped = mountEquipped;
            this.look = look;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)items.Count());
            foreach (var objectToSend in items)
            {
                 objectToSend.Serialize(writer);
            }
            writer.WriteBoolean(mountEquipped);
            look.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var itemsCount = reader.ReadUShort();
            var items_ = new Types.ItemForPreset[itemsCount];
            for (var itemsIndex = 0; itemsIndex < itemsCount; itemsIndex++)
            {
                 var objectToAdd = new Types.ItemForPreset();
                 objectToAdd.Deserialize(reader);
                 items_[itemsIndex] = objectToAdd;
            }
            items = items_;
            mountEquipped = reader.ReadBoolean();
            look = new Types.EntityLook();
            look.Deserialize(reader);
        }
    }
}