

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class Preset
    {
        public const short Id = 5013;
        public virtual short TypeId
        {
            get { return Id; }
        }
        
        public short id;
        
        public Preset()
        {
        }
        
        public Preset(short id)
        {
            this.id = id;
        }
        
        public virtual void Serialize(IDataWriter writer)
        {
            writer.WriteShort(id);
        }
        
        public virtual void Deserialize(IDataReader reader)
        {
            id = reader.ReadShort();
        }
    }
}