

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
    public class StatsPreset : Preset
    {
        public const short Id = 998;
        public override short TypeId
        {
            get { return Id; }
        }
        
        public IEnumerable<Types.SimpleCharacterCharacteristicForPreset> stats;
        
        public StatsPreset()
        {
        }
        
        public StatsPreset(short id, IEnumerable<Types.SimpleCharacterCharacteristicForPreset> stats)
         : base(id)
        {
            this.stats = stats;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort((short)stats.Count());
            foreach (var objectToSend in stats)
            {
                 objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            var statsCount = reader.ReadUShort();
            var stats_ = new Types.SimpleCharacterCharacteristicForPreset[statsCount];
            for (var statsIndex = 0; statsIndex < statsCount; statsIndex++)
            {
                 var objectToAdd = new Types.SimpleCharacterCharacteristicForPreset();
                 objectToAdd.Deserialize(reader);
                 stats_[statsIndex] = objectToAdd;
            }
            stats = stats_;
        }
    }
}