

//Generated by Kenshin
using System;
using System.Collections.Generic;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;

namespace Stump.DofusProtocol.D2oClasses
{
    [D2OClass("MapPosition", "com.ankamagames.dofus.datacenter.world")]
    [Serializable]
    public class MapPosition : IDataObject, IIndexedData
    {
        public const String MODULE = "MapPositions";
        public double id;
        public int posX;
        public int posY;
        public Boolean outdoor;
        public int capabilities;
        [I18NField]
        public int nameId;
        public List<List<int>> playlists;
        public int subAreaId;
        public int worldMap;
        public Boolean hasPriorityOnWorldmap;
        public Boolean allowPrism;
        public Boolean isTransition;
        public Boolean mapHasTemplate;
        public uint tacticalModeTemplateId;
        public Boolean hasPublicPaddock;
        int IIndexedData.Id
        {
            get { return (int)id; }
        }
        [D2OIgnore]
        public double Id
        {
            get { return this.id; }
            set { this.id = value; }
        }
        [D2OIgnore]
        public int PosX
        {
            get { return this.posX; }
            set { this.posX = value; }
        }
        [D2OIgnore]
        public int PosY
        {
            get { return this.posY; }
            set { this.posY = value; }
        }
        [D2OIgnore]
        public Boolean Outdoor
        {
            get { return this.outdoor; }
            set { this.outdoor = value; }
        }
        [D2OIgnore]
        public int Capabilities
        {
            get { return this.capabilities; }
            set { this.capabilities = value; }
        }
        [D2OIgnore]
        public int NameId
        {
            get { return this.nameId; }
            set { this.nameId = value; }
        }
        [D2OIgnore]
        public List<List<int>> Playlists
        {
            get { return this.playlists; }
            set { this.playlists = value; }
        }
        [D2OIgnore]
        public int SubAreaId
        {
            get { return this.subAreaId; }
            set { this.subAreaId = value; }
        }
        [D2OIgnore]
        public int WorldMap
        {
            get { return this.worldMap; }
            set { this.worldMap = value; }
        }
        [D2OIgnore]
        public Boolean HasPriorityOnWorldmap
        {
            get { return this.hasPriorityOnWorldmap; }
            set { this.hasPriorityOnWorldmap = value; }
        }
        [D2OIgnore]
        public Boolean AllowPrism
        {
            get { return this.allowPrism; }
            set { this.allowPrism = value; }
        }
        [D2OIgnore]
        public Boolean IsTransition
        {
            get { return this.isTransition; }
            set { this.isTransition = value; }
        }
        [D2OIgnore]
        public Boolean MapHasTemplate
        {
            get { return this.mapHasTemplate; }
            set { this.mapHasTemplate = value; }
        }
        [D2OIgnore]
        public uint TacticalModeTemplateId
        {
            get { return this.tacticalModeTemplateId; }
            set { this.tacticalModeTemplateId = value; }
        }
        [D2OIgnore]
        public Boolean HasPublicPaddock
        {
            get { return this.hasPublicPaddock; }
            set { this.hasPublicPaddock = value; }
        }
    }
}