using Newtonsoft.Json;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Misc
{
    public class DiscordTokenRelator
    {
        public static string FetchQuery = "SELECT * FROM discord_tokens";
    }

    [TableName("discord_tokens")]
    public class DiscordTokenRecord : AutoAssignedRecord<DiscordTokenRecord>, IAutoGeneratedRecord
    {
        public string Login { get; set; }

        public string Email { get; set; }

        public DateTime RegistreTime { get; set; }

        public DateTime RegistreEndTime { get; set; }

        public string Token { get; set; }

        public bool Active { get; set; }
    }
}