using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Misc
{
    public class EventTicketRelator
    {
        public static string FetchQuery = "SELECT * FROM player_event_tickets";
    }

    [TableName("player_event_tickets")]
    public class EventTicketRecord : AutoAssignedRecord<EventTicketRecord>, IAutoGeneratedRecord
    {
        public long AccountId { get; set; }

        public string AccountName { get; set; }

        public long GameTimeInSeconds { get; set; }

        public int TicketsQuantity { get; set; }

        public DateTime Date { get; set; }
    }
}