

//Generated by Kenshin
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Stump.Core.IO;
using Stump.DofusProtocol.Types;

namespace Stump.DofusProtocol.Messages
{
    public class CheckIntegrityMessage : Message
    {
        public const uint Id = 8109;
        public override uint MessageId => Id;
        
        public IEnumerable<sbyte> data;
        
        public CheckIntegrityMessage()
        { }
        
        public CheckIntegrityMessage(IEnumerable<sbyte> data)
        {
            this.data = data;
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarInt((int)data.Count());
            foreach (var objectToSend in data)
            {
                 writer.WriteSByte(objectToSend);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            var dataCount = reader.ReadVarInt();
            var data_ = new sbyte[dataCount];
            for (var dataIndex = 0; dataIndex < dataCount; dataIndex++)
            {
                 data_[dataIndex] = reader.ReadSByte();
            }
            data = data_;
        }
    }
}